# Variables defined here are to override role variables in /default/main.yml and apply to all nodes in the ansible inventory group with the same name as this file.
# For example, if you want to disable a specific STIG ID, the variable that controls that rule can be placed in here and disabled.

# HCX Connector environment specific variables
# Ubuntu variables for HCX Connector. Currently unused.
ubuntu_2404_defaults_auditd_rule_template_file: 'nsx_audit.STIG.rules'