control 'UBTU-24-901220' do
  title 'Ubuntu 24.04 LTS must record time stamps for audit records that can be mapped to Coordinated Universal Time (UTC) or Greenwich Mean Time (GMT).'
  desc 'If time stamps are not consistently applied and there is no common time reference, it is difficult to perform forensic analysis.

Time stamps generated by Ubuntu 24.04 LTS include date and time. Time is commonly expressed in Coordinated Universal Time (UTC), a modern continuation of Greenwich Mean Time (GMT), or local time with an offset from UTC.'
  desc 'check', 'Verify the time zone is configured to use UTC or GMT with the following command:

$ timedatectl status | grep -i "time zone"
Time zone: UTC (UTC, +0000)

If "Timezone" is not set to UTC or GMT, this is a finding.'
  desc 'fix', 'To configure the system time zone to use UTC or GMT, run the following command, replacing [ZONE] with UTC or GMT:

$ sudo timedatectl set-timezone [ZONE]'
  impact 0.3
  tag check_id: 'C-74853r1066947_chk'
  tag severity: 'low'
  tag gid: 'V-270820'
  tag rid: 'SV-270820r1066949_rule'
  tag stig_id: 'UBTU-24-901220'
  tag gtitle: 'SRG-OS-000359-GPOS-00146'
  tag fix_id: 'F-74754r1066948_fix'
  tag 'documentable'
  tag cci: ['CCI-001890']
  tag nist: ['AU-8 b']

  time_zone = command('timedatectl status | grep -i "time zone"').stdout.strip

  describe time_zone do
    it { should match 'UTC' }
  end
end
