---
# Vars file for CAP builds
var_rsyslog_authpriv_log: '/var/log/messages'
# Set to true if you want the playbook to install required packages. This requires access to a repo with the required packages.
run_rsyslog_install: false
run_openssl_fips_install: false
run_auditd_install: true
run_time_install: false
run_install_aide: true
run_selinux_install: true
var_pam_faillock_dir: '/var/log/faillock'
## 1 for enforcing and 0 for permissive
var_selinux_enforcing: 0

# disabled controls
run_etc_issue_dod: false
run_grub_boot_password: false
run_rsyslog_server: false
run_time_sync: false

# disable backups to keep a clean image
create_backups: false
