---
# defaults file for casa
catalina_base: /usr/lib/vmware-casa/casa-webapp
catalina_home: /usr/share/tomcat
server_xml_path: /usr/lib/vmware-casa/casa-webapp/conf/server.xml
web_xml_path: /usr/lib/vmware-casa/casa-webapp/conf/web.xml
catalina_prop_path: /usr/lib/vmware-casa/casa-webapp/conf/catalina.properties
default: "http://xmlns.jcp.org/xml/ns/javaee"

# VRPI-8X-000001
server_xml_maxthreads: '300'

# VRPI-8X-000014
# This may need special escaping if special characters are used like & and {# #}  {% raw %} and {% endraw %} at the beginning and end will get most of it
# Also &quot; needs to just be a " which turns into &quot;
server_xml_access_log_valve_pattern: '{% raw %}%t %h %l %u "%r" %s %b %D{% endraw %}'

# VRPI-8X-000070
# Set session timeout value to be less than equal to 30
web_xml_session_timeout: '30'

# VRPI-8X-000125
# This should not be set to -1
server_xml_connection_timeout: '60000'

# VRPI-8X-000126
# This should not be set to -1
server_xml_max_keepalive_requests: '50'
