---

- name: restart eam
  ansible.builtin.command: vmon-cli --restart eam
  register: output
  changed_when: output.rc == 0

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
