control 'VCFM-9X-000062' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must set the encoding for all text mime types to UTF-8.'
  desc  "
    Invalid user input occurs when a user inserts data or characters into a hosted application's data entry field and the hosted application is unprepared to process that data. This results in unanticipated application behavior, potentially leading to an application compromise. Invalid user input is one of the primary methods employed when attempting to compromise an application.

    An attacker can also enter Unicode into hosted applications in an effort to break out of the document home or root home directory or to bypass security checks.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/mimetype\\.assign/,/\\)/'|grep \"text/\"|grep -v \"charset=utf-8\"

    If the command returns any value, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/lighttpd/conf.d/mime.conf

    Navigate to the \"mimetype.assign\" block.

    Replace all the mappings whose assigned type is \"text/*\" with mappings for UTF-8 encoding. For example:

      \".log\"          =>      \"text/plain; charset=utf-8\",
      \".conf\"         =>      \"text/plain; charset=utf-8\",
      \".text\"         =>      \"text/plain; charset=utf-8\",
      \".txt\"          =>      \"text/plain; charset=utf-8\",
      \".spec\"         =>      \"text/plain; charset=utf-8\",
      \".dtd\"          =>      \"text/xml; charset=utf-8\",
      \".xml\"          =>      \"text/xml; charset=utf-8\",

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000251-WSR-000157'
  tag gid: 'V-VCFM-9X-000062'
  tag rid: 'SV-VCFM-9X-000062'
  tag stig_id: 'VCFM-9X-000062'
  tag cci: ['CCI-001310']
  tag nist: ['SI-10']

  describe command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/mimetype\\.assign/,/\\)/'|grep \"text/\"|grep -v \"charset=utf-8\"") do
    its('stdout') { should cmp '' }
  end
end
