control 'VCFM-9X-000066' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must not be configured to use the "mod_status" module.'
  desc  "
    Any application providing too much information in error logs and in administrative messages to the screen risks compromising the data and security of the application and system.

    VAMI must only generate error messages that provide information necessary for corrective actions without revealing sensitive or potentially harmful information in error logs and administrative messages. The \"mod_status\" module generates the status overview of the webserver.

    The information covers the following:

    - Uptime.
    - Average throughput.
    - Current throughput.
    - Active connections and their state.

    While this information is useful on a development system, production systems must not have \"mod_status\" enabled.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/server\\.modules/,/\\)/'|grep mod_status

    If any value is returned, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/lighttpd/modules.conf

    Remove the line containing \"mod_status\".

    Note: The line may be in an included config and not in the parent config.

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000266-WSR-000159'
  tag gid: 'V-VCFM-9X-000066'
  tag rid: 'SV-VCFM-9X-000066'
  tag stig_id: 'VCFM-9X-000066'
  tag cci: ['CCI-001312']
  tag nist: ['SI-11 a']

  modules = command("/#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/server\\.modules/,/\\)/'|sed -e 's/^[ ]*//'|grep mod_").stdout
  if !modules.empty?
    modules.split.each do |result|
      describe result do
        it { should_not match /mod_status/ }
      end
    end
  else
    describe 'No modules found...skipping.' do
      skip 'No modules found...skipping.'
    end
  end
end
