control 'VCFM-9X-000061' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must restrict the ability of users to launch denial-of-service (DoS) attacks against other information systems or networks.'
  desc  "
    In UNIX and related computer operating systems, a file descriptor is an indicator used to access a file or other input/output resource, such as a pipe or network connection. File descriptors index into a per-process file descriptor table maintained by the kernel, which in turn indexes into a systemwide table of files opened by all processes, called the file table.

    As a single-threaded server, Lighttpd must be limited in the number of file descriptors that can be allocated. This will prevent Lighttpd from being used in a form of DoS attack against the operating system.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|grep \"server.max-fds\"

    Example result:

    server.max-fds=2048

    If \"server.max-fds\" is not set to 2048 or less, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/lighttpd/lighttpd.conf

    Add or reconfigure the following value:

    server.max-fds = 2048

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000246-WSR-000149'
  tag gid: 'V-VCFM-9X-000061'
  tag rid: 'SV-VCFM-9X-000061'
  tag stig_id: 'VCFM-9X-000061'
  tag cci: ['CCI-001094']
  tag nist: ['SC-5 (1)']

  runtime = command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')}").stdout

  describe parse_config(runtime).params['server.max-fds'] do
    it { should cmp <= 2048 }
  end
end
