---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-pinniped-runasgrp
spec:
    match:
      scope: Namespaced
      kinds:
        - apiGroups: ["*"]
          kinds: ["Pod"]
      namespaces:
      - pinniped-supervisor
      labelSelector:
        matchLabels:
         app: pinniped-post-deploy-controller
    applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
    location: "spec.containers[name:*].securityContext.runAsGroup"
    parameters:
      pathTests:
      - subPath: "spec.containers[name:*].securityContext.runAsGroup"
        condition: MustNotExist
      assign:
        value: 65532
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-tanzu-auth-runasusr
spec:
    match:
      scope: Namespaced
      kinds:
        - apiGroups: ["*"]
          kinds: ["Pod"]
      namespaces:
      - tanzu-auth
      labelSelector:
        matchLabels:
         app: tanzu-auth-controller-manager
    applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
    location: "spec.containers[name:*].securityContext.runAsUser"
    parameters:
      pathTests:
      - subPath: "spec.containers[name:*].securityContext.runAsUser"
        condition: MustNotExist
      assign:
        value: 65532
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-tanzu-auth-runasgrp
spec:
    match:
      scope: Namespaced
      kinds:
        - apiGroups: ["*"]
          kinds: ["Pod"]
      namespaces:
      - tanzu-auth
      labelSelector:
        matchLabels:
         app: tanzu-auth-controller-manager
    applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
    location: "spec.containers[name:*].securityContext.runAsGroup"
    parameters:
      pathTests:
      - subPath: "spec.containers[name:*].securityContext.runAsGroup"
        condition: MustNotExist
      assign:
        value: 65532
---
apiVersion: mutations.gatekeeper.sh/v1alpha1
kind: Assign
metadata:
  name: assign-pinniped-runasusr
spec:
    match:
      scope: Namespaced
      kinds:
        - apiGroups: ["*"]
          kinds: ["Pod"]
      namespaces:
      - pinniped-supervisor
      labelSelector:
        matchLabels:
         app: pinniped-post-deploy-controller
    applyTo:
    - groups: [""]
      kinds: ["Pod"]
      versions: ["v1"]
    location: "spec.containers[name:*].securityContext.runAsUser"
    parameters:
      pathTests:
      - subPath: "spec.containers[name:*].securityContext.runAsUser"
        condition: MustNotExist
      assign:
        value: 65532
