control 'ESXI-67-000058' do
  title "The ESXi host must enable BPDU filter on the host to prevent being
locked out of physical switch ports with Portfast and BPDU Guard enabled."
  desc  "BPDU Guard and Portfast are commonly enabled on the physical switch to
which the ESXi host is directly connected to reduce the STP convergence delay.

    If a BPDU packet is sent from a virtual machine on the ESXi host to the
physical switch so configured, a cascading lockout of all the uplink interfaces
from the ESXi host can occur. To prevent this type of lockout, BPDU Filter can
be enabled on the ESXi host to drop any BPDU packets being sent to the physical
switch.

    The caveat is that certain SSL VPNs that use Windows bridging capability
can legitimately generate BPDU packets. The administrator should verify that
there are no legitimate BPDU packets generated by virtual machines on the ESXi
host prior to enabling BPDU Filter. If BPDU Filter is enabled in this
situation, enabling Reject Forged Transmits on the virtual switch port group
adds protection against Spanning Tree loops.
  "
  desc  'rationale', ''
  desc  'check', "
    From the vSphere Client, select the ESXi host and go to Configure >> System
>> Advanced System Settings.

    Select the \"Net.BlockGuestBPDU\" value and verify it is set to \"1\".

    or

    From a PowerCLI command prompt while connected to the ESXi host, run the
following command:

    Get-VMHost | Get-AdvancedSetting -Name Net.BlockGuestBPDU

    If the \"Net.BlockGuestBPDU\" setting is not set to \"1\", this is a
finding.
  "
  desc 'fix', "
    From the vSphere Client, select the ESXi host and go to Configure >> System
>> Advanced System Settings.

    Click \"Edit\", select the \"Net.BlockGuestBPDU\" value, and configure it
to \"1\".

    or

    From a PowerCLI command prompt while connected to the ESXi host, run the
following commands:

    Get-VMHost | Get-AdvancedSetting -Name Net.BlockGuestBPDU |
Set-AdvancedSetting -Value 1
  "
  impact 0.3
  tag severity: 'low'
  tag gtitle: 'SRG-OS-000480-VMM-002000'
  tag gid: 'V-239312'
  tag rid: 'SV-239312r674865_rule'
  tag stig_id: 'ESXI-67-000058'
  tag fix_id: 'F-42504r674864_fix'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  command = "(Get-VMHost -Name #{input('vmhostName')}) | Get-AdvancedSetting -Name Net.BlockGuestBPDU | Select-Object -ExpandProperty Value"
  describe powercli_command(command) do
    its('stdout.strip') { should cmp '1' }
  end
end
