- name: "[Common] sysctl"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
  with_items: 
  - name: net.ipv4.conf.all.accept_source_route
    value: 0
  - name: net.ipv4.conf.default.accept_source_route
    value: 0
  - name: net.ipv4.icmp_echo_ignore_broadcasts
    value: 1
  - name: net.ipv4.conf.all.send_redirects
    value: 0
  - name: net.ipv4.conf.default.send_redirects
    value: 0
  - name: net.ipv6.conf.all.accept_source_route
    value: 0
  - name: net.ipv4.conf.default.accept_redirects
    value: 0
  - name: kernel.randomize_va_space
    value: 2
  - name: net.ipv6.conf.all.disable_ipv6
    value: 0
  - name: net.ipv4.tcp_syncookies
    value: 1
  tags:
  - V-238333
  - V-238369

- name: "sysctl: --protect-kernel-defaults"
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
  with_items:
  - name: vm.overcommit_memory
    value: 1
  - name: kernel.panic
    value: 10
  - name: kernel.panic_on_oops
    value: 1
  when:
    install_protect_kernel_defaults

- name: "sysctl: fs.suid_dumpable "
  blockinfile:
    dest: /etc/systemd/coredump.conf
    block: |
      Storage=none
      ProcessSizeMax=0
    create: yes
