- name: check nopasswd !authenticate
  command: egrep -Ri '(nopasswd|!authenticate)' /etc/sudoers /etc/sudoers.d
  register: nopasswd_user
  tags:
  - medium

- name: print nopasswd !authenticate message
  debug:
    msg: >
      User(s) not requiring to re-authenticate for privilege escalation and changing roles.\n
      {{ nopasswd_user.stdout }}
  when:
    nopasswd_user is defined
  tags:
  - medium
