apiVersion: crd.antrea.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: tanzu-sec-gen-apiserver
  namespace: secretgen-controller
spec:
  priority: 5
  tier: securityops
  appliedTo:
    - podSelector:
        matchLabels:
         app: secretgen-controller
  egress:
    - action: Allow
      toServices:
       - name: kubernetes
         namespace: default
      name: AllowToApiserver
