---

###################################################################################################################################
# TDFW-3X-000005 - The NSX-T Distributed Firewall must generate traffic log entries containing information to establish the details of the event.
- name: TDFW-3X-000005 - The NSX-T Distributed Firewall must generate traffic log entries containing information to establish the details of the event.
  tags: [TDFW-3X-000005]
  when: run_dfw_rule_logging | bool
  block:
    - name: TDFW-3X-000005 - Find DFW rules without logging enabled excluding the default layer 2 rule
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:Rule%20AND%20logged:false%20AND%20!id:default-layer2-rule%20AND%20parent_path:?infra?domains?default?security-policies*)&included_fields=id,rule_id,logged,path,sequence_number,action"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
      register: dfwruleswo_logging
      changed_when: false

    - name: TDFW-3X-000005 - Enable logging on DFW rules without logging enabled excluding the default layer 2 rule
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1{{ item.path }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './enable_logging_dfw_rule.json.j2') | to_json }}"
        body_format: json
        status_code: 200
      with_items:
        - "{{ dfwruleswo_logging.json.results }}"
      register: response
      when:
        - dfwruleswo_logging.json.result_count != 0
      changed_when:
        - response.status == 200

###################################################################################################################################
# TDFW-3X-000019 - The NSX-T Distributed Firewall must block outbound traffic containing denial-of-service (DoS) attacks to protect against the use of internal information systems to launch any DoS attacks against other networks or endpoints.
- name: TDFW-3X-000019 - The NSX-T Distributed Firewall must deny network communications traffic by default and allow network communications traffic by exception.
  tags: [TDFW-3X-000019, TDFW-3X-000028]
  when: run_dfw_floodprotprof | bool
  block:
    - name: TDFW-3X-000019-28 - Check if flood protection profiles exists
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:(DistributedFloodProtectionProfile))"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
      register: dfw_floodprot_prof
      changed_when: false

    - name: TDFW-3X-000019-28 - Create a flood protection profile if doesn't exist
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/flood-protection-profiles/{{ var_dfw_fpp_name }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './dfw_create_flood_prot_prof.json.j2') }}"
        body_format: json
        status_code: 200
      register: response_create
      when:
        - dfw_floodprot_prof.json.result_count == 0
      changed_when:
        - response_create.status == 200

    - name: TDFW-3X-000019-28 - Update existing flood protection profiles
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/flood-protection-profiles/{{ item.id }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './dfw_upd_flood_prot_prof.json.j2') | to_json }}"
        body_format: json
        status_code: 200
      with_items:
        - "{{ dfw_floodprot_prof.json.results }}"
      register: response_update
      when:
        - dfw_floodprot_prof.json.result_count != 0
        - (item.enable_syncache != var_dfw_fpp_syncache) or
          (item.enable_rst_spoofing != var_dfw_fpp_rst_spoofing) or
          (item.udp_active_flow_limit != var_dfw_fpp_udp_active_flow_limit) or
          (item.icmp_active_flow_limit != var_dfw_fpp_icmp_active_flow_limit) or
          (item.tcp_half_open_conn_limit != var_dfw_fpp_tcp_half_open_conn_limit) or
          (item.other_active_conn_limit != var_dfw_fpp_other_active_conn_limit)
      changed_when:
        - response_update.status == 200

###################################################################################################################################
# TDFW-3X-000021 - The NSX-T Distributed Firewall must deny network communications traffic by default and allow network communications traffic by exception.
- name: TDFW-3X-000021 - The NSX-T Distributed Firewall must deny network communications traffic by default and allow network communications traffic by exception.
  tags: [TDFW-3X-000021]
  when: run_dfw_default_rule_action | bool
  block:
    - name: TDFW-3X-000021 - Find DFW default layer 3 rule
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/domains/default/security-policies/default-layer3-section/rules/default-layer3-rule"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
      register: dfwrules_layerthree
      changed_when: false

    - name: TDFW-3X-000021 - Update DFW default layer 3 rule action to desired value
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/domains/default/security-policies/default-layer3-section/rules/default-layer3-rule"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './disable_default_layer3_traffic.json.j2') | to_json }}"
        body_format: json
        status_code: 200
      register: response
      when:
        - dfwrules_layerthree.json.action == "ALLOW"
      changed_when:
        - response.status == 200

##################################################################################################################################
# TDFW-3X-000026 - The NSX-T Distributed Firewall must be configured to send traffic log entries to a central audit server for management and configuration of the traffic log entries.
# This fix is covered as part of the ESXi STIG.

###################################################################################################################################
- name: TDFW-3X-000026
  tags: [TDFW-3X-000026]
  when: run_dfw_syslog | bool
  block:
    - name: TDFW-3X-000026 - The NSX-T Distributed Firewall must be configured to send traffic log entries to a central audit server for management and configuration of the traffic log entries.
      ansible.builtin.debug:
        msg: "TDFW-3X-000026 - This remediation is covered as part of the ESXi STIG."
      changed_when: false

##################################################################################################################################
# TDFW-3X-000028 - The NSX-T Distributed Firewall must employ filters that prevent or limit the effects of all types of commonly known denial-of-service (DoS) attacks, including flooding, packet sweeps, and unauthorized port scanning.
# This is covered as part of TDFW-3X-000019

###################################################################################################################################
# TDFW-3X-000036 - The NSX-T Distributed Firewall must configure SpoofGuard to block outbound IP packets that contain illegitimate packet attributes.
- name: TDFW-3X-000036 - The NSX-T Distributed Firewall must configure SpoofGuard to block outbound IP packets that contain illegitimate packet attributes.
  tags: [TDFW-3X-000036]
  when: run_dfw_spoofguard_prof | bool
  block:
    - name: TDFW-3X-000036 - List SpoofGuard segment profiles excluding the default profile which cannot be modified
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:SpoofGuardProfile%20AND%20!id:default-spoofguard-profile)"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
      register: dfw_spfgrd_prof_list
      changed_when: false

    - name: TDFW-3X-000036 - Create SpoofGuard segment profile with port binding enabled if none exist
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/spoofguard-profiles/{{ var_dfw_spoofguard_profile_name }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PUT
        body: "{{ lookup('template', './dfw_spoof_guard_prof_create.json.j2') }}"
        body_format: json
        status_code: 200
      when:
        - dfw_spfgrd_prof_list.json.result_count == 0
      register: dfw_spfgrd_prof_wportbind_create
      changed_when:
        - dfw_spfgrd_prof_wportbind_create.status == 200

    - name: TDFW-3X-000036 - Update SpoofGuard segment profiles with port binding disabled
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/spoofguard-profiles/{{ item.id }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './dfw_spoof_guard_prof_patch.json') }}"
        body_format: json
        status_code: 200
      with_items:
        - "{{ dfw_spfgrd_prof_list.json.results }}"
      when:
        - dfw_spfgrd_prof_list.json.result_count != 0
        - not item.address_binding_allowlist
      register: dfw_spfgrd_prof_wportbind_update
      changed_when:
        - dfw_spfgrd_prof_wportbind_update.status == 200

    - name: TDFW-3X-000036 - Get all segments
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/segments"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
      register: dfwsegmentlist
      changed_when: false

    - name: TDFW-3X-000036 - Loop through segments and update Spoofguard profile if necessary
      ansible.builtin.include_tasks:
        file: dfw_segments_update_spoofguard.yml
      with_items: "{{ dfwsegmentlist.json.results }}"
      when:
        - dfwsegmentlist.json.result_count != 0

###################################################################################################################################
- name: TDFW-3X-000042
  tags: [TDFW-3X-000042]
  when: run_dfw_verify_time_based_rules | bool
  block:
    - name: TDFW-3X-000042 - The NSX-T Distributed Firewall must verify time-based firewall rules.
      ansible.builtin.debug:
        msg: "TDFW-3X-000042 - This control must be manually remediated."
      changed_when: false
