control 'UAGA-8X-000166' do
  title 'The UAG must only generate messages that provide information necessary for corrective actions without revealing sensitive or potentially harmful information in error logs and administrative messages.'
  desc  'Any application providing too much information in error logs and in administrative messages to the screen risks compromising the data and security of the application and system. The structure and content of error messages needs to be carefully considered by the organization and development team. The application server must not log sensitive information such as passwords, private keys, or other sensitive data. This requirement pertains to logs that are generated by the application server and application server processes, not the applications that may reside on the application server. Those errors are out of the scope of these requirements.'
  desc  'rationale', ''
  desc  'check', "
    Login to the UAG administrative interface as an administrator.

    Select \"Configure Manually\".

    Navigate to Support Settings >> Log Level Settings. Click the \"Gear\" icon to edit.

    If the log level settings does not contain an entry for \"All - INFO\", this is a finding.

    Note: DEBUG and TRACE log levels must be applied only during troubleshooting as these levels can reduce performance and increase the verbose log messages. After you complete troubleshooting using the DEBUG or TRACE log levels, the log level must be reset to INFO or the component or sub-component must be removed from the log settings.
  "
  desc 'fix', "
    Login to the UAG administrative interface as an administrator.

    Select \"Configure Manually\".

    Navigate to Support Settings >> Log Level Settings. Click the \"Gear\" icon to edit.

    Remove any unnecessary log components.

    Remove any components with a \"DEBUG\" or \"TRACE\" level, unless actively troubleshooting an issue.

    Ensure, at a minimum, that an entry for \"All - INFO\" is added.
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-NET-000512-ALG-000062'
  tag gid: 'V-UAGA-8X-000166'
  tag rid: 'SV-UAGA-8X-000166'
  tag stig_id: 'UAGA-8X-000166'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  result = uaghelper.runrestcommand('rest/v1/config/system')

  describe result do
    its('status') { should cmp 200 }
  end

  unless result.status != 200
    jsoncontent = json(content: result.body)
    if jsoncontent['snmpEnabled'] == true
      describe jsoncontent['snmpSettings']['version'] do
        it { should cmp 'V3' }
      end
    else
      describe jsoncontent['snmpEnabled'] do
        it { should cmp false }
      end
    end
  end
end
