control 'CFPG-4X-000021' do
  title 'The SDDC Manager PostgreSQL service must use UTC for log timestamps.'
  desc  "
    If time stamps are not consistently applied and there is no common time reference, it is difficult to perform forensic analysis.

    Time stamps generated by PostgreSQL must include date and time. Time is commonly expressed in Coordinated Universal Time (UTC), a modern continuation of Greenwich Mean Time (GMT), or local time with an offset from UTC.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following command:

    # psql -h localhost -U postgres -A -t -c \"SHOW log_timezone\"

    Expected result:

    UTC

    If the output does not match the expected result, this is a finding.
  "
  desc 'fix', "
    At the command prompt, run the following commands:

    # psql -h localhost -U postgres -c \"ALTER SYSTEM SET log_timezone TO 'UTC';\"
    # psql -h localhost -U postgres -c \"SELECT pg_reload_conf();\"
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000374-DB-000322'
  tag satisfies: ['SRG-APP-000375-DB-000323']
  tag gid: 'V-CFPG-4X-000021'
  tag rid: 'SV-CFPG-4X-000021'
  tag stig_id: 'CFPG-4X-000021'
  tag cci: ['CCI-001889', 'CCI-001890']
  tag nist: ['AU-8 b']

  sql = postgres_session("#{input('postgres_user')}", "#{input('postgres_pass')}", "#{input('postgres_host')}")
  sqlquery = 'SHOW log_timezone;'

  describe sql.query(sqlquery) do
    its('output') { should be_in "#{input('pg_log_timezone')}" }
  end
end
