---

- name: "T0RT-3X-000013 - Get external interfaces with multicast enabled for Tier-0 Gateway: {{ var_outer_t0.id }}"
  ansible.builtin.uri:
    url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:Tier0Interface%20AND%20type:EXTERNAL%20AND%20multicast.enabled:true%20AND%20parent_path:?infra?tier-0s?{{ var_outer_t0.id }}*)"
    validate_certs: false
    headers:
      Cookie: "{{ var_jsession_id }}"
      X-XSRF-TOKEN: "{{ var_session_token }}"
    method: GET
    status_code: 200
  register: t0interfaces
  changed_when: false

- name: "T0RT-3X-000013 - Disable multicast on interfaces for Tier-0 Gateway: {{ var_outer_t0.id }}"
  ansible.builtin.uri:
    url: "https://{{ var_nsx_manager }}/policy/api/v1{{ item.path }}"
    validate_certs: false
    headers:
      Cookie: "{{ var_jsession_id }}"
      X-XSRF-TOKEN: "{{ var_session_token }}"
    method: PATCH
    body: "{{ lookup('template', './t0rt_disable_multicast_on_interface.json.j2') }}"
    body_format: json
    status_code: 200
  when:
    - t0interfaces.json.result_count != 0
    - item.id not in var_t0rt_gateway_interfaces_with_multicast_enabled
  with_items:
    - "{{ t0interfaces.json.results }}"
  register: response
  changed_when:
    - response.status == 200
