control 'WOAD-3X-000080' do
  title 'The Workspace ONE Access vPostgres instance must use UTC for log timestamps.'
  desc  'If time stamps are not consistently applied and there is no common time reference, it is difficult to perform forensic analysis. Time stamps generated by VMware Postgres must include date and time expressed in Coordinated Universal Time (UTC), a modern continuation of Greenwich Mean Time (GMT).'
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, execute the following command:

    #  /opt/vmware/vpostgres/9.6/bin/psql -U postgres -A -t -c \"SHOW log_timezone\"

    Expected result:

    UTC

    If the output does not match the expected result, this is a finding.

    Note: For a non-clustered vRSLCM deployed instance you may be prompted for the postgres users password which is available at /usr/local/horizon/conf/db.pwd.
  "
  desc 'fix', "
    At the command prompt, execute the following command(s):

    # /opt/vmware/vpostgres/9.6/bin/psql -U postgres -c \"ALTER SYSTEM SET log_timezone TO 'UTC';\"

    # /opt/vmware/vpostgres/9.6/bin/psql -U postgres -c \"SELECT pg_reload_conf();\"

    Note: For a non-clustered vRSLCM deployed instance you may be prompted for the postgres users password which is available at /usr/local/horizon/conf/db.pwd.
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000374-DB-000322'
  tag gid: 'V-WOAD-3X-000080'
  tag rid: 'SV-WOAD-3X-000080'
  tag stig_id: 'WOAD-3X-000080'
  tag cci: ['CCI-001890']
  tag nist: ['AU-8 b']

  timezones = ['Etc/UTC', 'UTC']
  clustered = input('clustered')

  if clustered
    describe command('/opt/vmware/vpostgres/9.6/bin/psql -U postgres -A -t -c "SHOW log_timezone;"') do
      its('stdout.strip') { should be_in timezones }
    end
  else
    sqlpw = file("#{input('postgres_pw_file')}").content.strip
    sql = postgres_session("#{input('postgres_user')}", sqlpw, "#{input('postgres_host')}")
    sqlquery = 'SHOW log_timezone;'

    describe sql.query(sqlquery) do
      its('output') { should be_in timezones }
    end
  end
end
