control 'VCLD-80-000099' do
  title 'The vCenter VAMI service must implement HTTP Strict Transport Security (HSTS).'
  desc  'HTTP Strict Transport Security (HSTS) instructs web browsers to only use secure connections for all future requests when communicating with a web site. Doing so helps prevent SSL protocol attacks, SSL stripping, cookie hijacking, and other attempts to circumvent SSL protection.'
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following command:

    # /opt/vmware/sbin/vami-lighttpd -p -f /opt/vmware/etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/setenv\\.add-response-header/,/\\)/'|sed -e 's/^[ ]*//'|grep \"Strict-Transport-Security\"

    Expected result:

    \"Strict-Transport-Security\" => \"max-age=31536000; includeSubDomains\",

    If the output does not match the expected result, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://kb.vmware.com/s/article/2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/applmgmt/appliance/lighttpd.conf

    Locate the \"setenv.add-response-header\" parameter and add or update the following value:

    \"Strict-Transport-Security\" => \"max-age=31536000; includeSubDomains\",

    Note: The last line in the parameter does not need a trailing comma.

    Restart the service with the following command:

    # vmon-cli --restart applmgmt
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000516-WSR-000174'
  tag gid: 'V-VCLD-80-000099'
  tag rid: 'SV-VCLD-80-000099'
  tag stig_id: 'VCLD-80-000099'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  describe command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/setenv\.add-response-header/,/\)/'|sed -e 's/^[ ]*//'|grep Strict-Transport-Security") do
    its('stdout.strip') { should cmp '"Strict-Transport-Security" => "max-age=31536000; includeSubDomains",' }
  end
end
