control 'UBTU-22-252020' do
  title 'Ubuntu 22.04 LTS must record time stamps for audit records that can be mapped to Coordinated Universal Time (UTC).'
  desc 'If time stamps are not consistently applied and there is no common time reference, it is difficult to perform forensic analysis.

Time stamps generated by the operating system include date and time. Time is commonly expressed in UTC or local time with an offset from UTC.'
  desc 'check', 'Verify the time zone is configured to use UTC by using the following command:

     $ timedatectl status | grep -i "time zone"
     Time zone: Etc/UTC (UTC, +0000)

If "Time zone" is not set to UTC, this is a finding.'
  desc 'fix', 'To Configure Ubuntu 22.04 LTS time zone to use UTC, run the following command:

     $ sudo timedatectl set-timezone Etc/UTC'
  impact 0.3
  ref 'DPMS Target Canonical Ubuntu 22.04 LTS'
  tag check_id: 'C-64250r953374_chk'
  tag severity: 'low'
  tag gid: 'V-260521'
  tag rid: 'SV-260521r958788_rule'
  tag stig_id: 'UBTU-22-252020'
  tag gtitle: 'SRG-OS-000359-GPOS-00146'
  tag fix_id: 'F-64158r953375_fix'
  tag 'documentable'
  tag cci: ['CCI-001890']
  tag nist: ['AU-8 b']

  time_zone = command('timedatectl status | grep -i "time zone"').stdout.strip

  describe time_zone do
    it { should match 'UTC' }
  end
end
