apiVersion: crd.antrea.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: tanzu-auth-apiserver
  namespace: tanzu-auth
spec:
  priority: 5
  tier: securityops
  appliedTo:
    - podSelector:
        matchLabels:
         app: tanzu-auth-controller-manager
  egress:
    - action: Allow
      toServices:
       - name: kubernetes
         namespace: default
      name: AllowToKubeSystem
