# vCenter 7.0 Appliance STIG vPostgres Ansible Role

---
#---------- Ansible version 2.8.5 --------#

############################################

# Backup files that may be modified in case restoration is needed

- name: Create time stamp
  set_fact:
    backup_timestamp: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
  tags:
  - perfcharts
  when:
  - create_backups | bool

- name: Backup files...if restoring be sure to restore permissions that original file had!!
  copy:
    remote_src: yes
    src: "{{ item }}"
    dest: "{{ item }}_{{ backup_timestamp }}.bak"
  with_items:
    - '{{ var_postgres_conf_file }}'
    - '{{ var_postgres_hba_conf_file }}'
  tags:
  - vpostgres
  when:
  - create_backups | bool

############################################

# Title: VMware Postgres must limit the number of connections.
# VCPG-70-000001 requires manual remediation

############################################

# Title: VMware Postgres log files must contain required fields.

- name: VCPG-70-000002 - VMware Postgres log files must contain required fields.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^log_line_prefix.*$'
    line: log_line_prefix = {{ var_postgres_conf_log_line_prefix }}
    firstmatch: yes
  tags:
  - VCPG-70-000002
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_log_line_prefix | bool

############################################

# Title: VMware Postgres configuration files must not be accessible by unauthorized users.

- name: VCPG-70-000003 - VMware Postgres configuration files must not be accessible by unauthorized users.
  find:
    paths: /storage/db/vpostgres
    file_type: file
    patterns: '*conf*'
  register: pgconffiles
  tags:
  - VCPG-70-000003
  - perms
  - vpostgres
  when:
  - run_postgres_conf_file_permissions | bool

- name: VCPG-70-000003 - VMware Postgres configuration files must not be accessible by unauthorized users.
  file:
    path: "{{ item.path }}"
    state: file
    mode: 0600
    owner: vpostgres
    group: users
  with_items: "{{ pgconffiles.files }}"
  tags:
  - VCPG-70-000003
  - perms
  - vpostgres
  when:
  - run_postgres_conf_file_permissions | bool

############################################

# Title: VMware Postgres must be configured to overwrite older logs when necessary.

- name: VCPG-70-000004 - VMware Postgres must be configured to overwrite older logs when necessary.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^log_truncate_on_rotation.*$'
    line: log_truncate_on_rotation = {{ var_postgres_conf_log_truncate_on_rotation }}
    firstmatch: yes
  tags:
  - VCPG-70-000004
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_log_truncate_on_rotation | bool

############################################

# Title: VMware Postgres database must protect log files from unauthorized access and modification.

- name: VCPG-70-000005 - VMware Postgres database must protect log files from unauthorized access and modification.
  find:
    paths: '{{ var_postgres_log_path }}'
    file_type: file
    patterns: '*'
  register: pglogfiles
  tags:
  - VCPG-70-000005
  - perms
  - vpostgres
  when:
  - run_postgres_log_file_permissions | bool

- name: VCPG-70-000005 - VMware Postgres database must protect log files from unauthorized access and modification.
  file:
    path: "{{ item.path }}"
    state: file
    mode: 0600
    owner: vpostgres
    group: users
  with_items: "{{ pglogfiles.files }}"
  tags:
  - VCPG-70-000005
  - perms
  - vpostgres
  when:
  - run_postgres_log_file_permissions | bool

############################################

# Title: All VCDB tables must be owned by the 'vc' user account.
# VCPG-70-000006 requires manual remediation

############################################

# Title: VMware Postgres must limit modify privileges to authorized accounts.
# VCPG-70-000007 requires manual remediation

############################################

# Title: VMware Postgres must be configured to use the correct port.

- name: VCPG-70-000008 - VMware Postgres must be configured to use the correct port.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^port.*$'
    line: port = {{ var_postgres_conf_port }}
    firstmatch: yes
  tags:
  - VCPG-70-000008
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_port | bool

############################################

# Title: VMware Postgres must require authentication on all connections.

- name: VCPG-70-000009 - VMware Postgres must require authentication on all connections.
  replace:
    path: '{{ var_postgres_hba_conf_file }}'
    regexp: ^(local.*)(trust)(.*)$
    replace: \1 md5 \3
  tags:
  - VCPG-70-000009
  - conf
  - vpostgres
  notify:
  - restart vpostgres
  when:
  - run_postgres_hba_conf_local_trust | bool

############################################

# Title: The vPostgres database must use md5 for authentication.

- name: VCPG-70-000010 - The vPostgres database must use md5 for authentication.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^password_encryption.*$'
    line: password_encryption = {{ var_postgres_conf_pw_encryption }}
    firstmatch: yes
  tags:
  - VCPG-70-000010
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_ps_encryption | bool

############################################

# Title: VMware Postgres must be configured to use TLS.

- name: VCPG-70-000011 - VMware Postgres must be configured to use TLS.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^ssl =.*$'
    line: ssl = {{ var_postgres_conf_ssl }}
    firstmatch: yes
  tags:
  - VCPG-70-000011
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_ssl | bool

############################################

# Title: VMware Postgres must enforce authorized access to all PKI private keys.

- name: VCPG-70-000012 - VMware Postgres must enforce authorized access to all PKI private keys.
  file:
    path: /storage/db/vpostgres_ssl/server.key
    state: file
    mode: 0600
    owner: vpostgres
    group: users
  tags:
  - VCPG-70-000012
  - perms
  - vpostgres
  when:
  - run_postgres_key_file_permissions | bool

############################################

# Title: VMware Postgres must use FIPS 140-2 approved TLS ciphers.

- name: VCPG-70-000013 - VMware Postgres must use FIPS 140-2 approved TLS ciphers.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^ssl_ciphers.*$'
    line: ssl_ciphers = {{ var_postgres_conf_ssl_ciphers }}
    firstmatch: yes
  tags:
  - VCPG-70-000013
  - conf
  - vpostgres
  notify:
  - restart vpostgres
  when:
  - run_postgres_conf_ssl_ciphers | bool

############################################

# Title: VMware Postgres must write log entries to disk prior to returning operation success or failure.

- name: VCPG-70-000014 - VMware Postgres must write log entries to disk prior to returning operation success or failure.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    firstmatch: yes
  with_items:
  - { line: 'fsync = {{ var_postgres_conf_fsync }}', regexp: '^fsync =.*$' }
  - { line: 'full_page_writes = {{ var_postgres_conf_full_page_writes }}', regexp: '^full_page_writes =.*$' }
  - { line: 'synchronous_commit = {{ var_postgres_conf_synchronous_commit }}', regexp: '^synchronous_commit =.*$' }
  tags:
  - VCPG-70-000014
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_write_log_entries | bool

############################################

# Title: VMware Postgres must not allow schema access to unauthorized accounts.
# VCPG-70-000015 requires manual remediation

############################################

# Title: VMware Postgres must provide non-privileged users with minimal error information.

- name: VCPG-70-000016 - VMware Postgres must provide non-privileged users with minimal error information.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^client_min_messages.*$'
    line: client_min_messages = {{ var_postgres_conf_client_min_messages }}
    firstmatch: yes
  tags:
  - VCPG-70-000016
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_client_min_messages | bool

############################################

# Title: VMware Postgres must have log collection enabled.

- name: VCPG-70-000017 - VMware Postgres must have log collection enabled.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^logging_collector.*$'
    line: logging_collector = {{ var_postgres_conf_logging_collector }}
    firstmatch: yes
  tags:
  - VCPG-70-000017
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_logging_collector | bool

############################################

# Title: VMware Postgres must be configured to log to stderr.

- name: VCPG-70-000018 - VMware Postgres must be configured to log to stderr.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^log_destination.*$'
    line: log_destination = {{ var_postgres_conf_log_destination }}
    firstmatch: yes
  tags:
  - VCPG-70-000018
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_log_destination | bool

############################################

# Title: Rsyslog must be configured to monitor VMware Postgres logs.

- name: VCPG-70-000019 - Rsyslog must be configured to monitor VMware Postgres logs.
  template:
    src: vmware-services-vmware-postgres-archiver.conf.j2
    dest: /etc/vmware-syslog/vmware-services-vmware-postgres-archiver.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  notify:
  - restart syslog
  tags:
  - VCPG-70-000019
  - syslog
  - vpostgres
  when:
  - run_postgres_syslog_config | bool

- name: VCPG-70-000019 - Rsyslog must be configured to monitor VMware Postgres logs.
  template:
    src: vmware-services-vmware-vpostgres.conf.j2
    dest: /etc/vmware-syslog/vmware-services-vmware-vpostgres.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  notify:
  - restart syslog
  tags:
  - VCPG-70-000019
  - syslog
  - vpostgres
  when:
  - run_postgres_syslog_config | bool

############################################

# Title: VMware Postgres must use UTC for log timestamps.

- name: VCPG-70-000020 - VMware Postgres must use UTC for log timestamps.
  lineinfile:
    path: '{{ var_postgres_conf_file }}'
    state: present
    regexp: '^log_timezone.*$'
    line: log_timezone = {{ var_postgres_conf_log_timezone }}
    firstmatch: yes
  tags:
  - VCPG-70-000020
  - conf
  - vpostgres
  notify:
  - reload vpostgres config
  when:
  - run_postgres_conf_log_timezone | bool
