---
# Example vars file to use when running this playbook to update any required variables
create_backups: false
run_etc_issue_dod: true
var_rsyslog_authpriv_log: '/var/log/messages'
var_rsyslog_server_name: 'syslog.test.local'
var_rsyslog_server_port: '514'
## udp, tcp, or tls
var_rsyslog_server_protocol: 'tcp'
# Set to true if you want the playbook to install required packages. This requires access to a repo with the required packages.
run_rsyslog_install: true
run_openssl_fips_install: true
run_auditd_install: true
run_time_install: true
run_install_aide: true
run_selinux_install: true
var_time_servers:
  - 'time-a-g.nist.gov'
  - 'time-b-g.nist.gov'
## ntpd, chrony, or timesyncd
var_time_type: 'ntpd'
var_pam_faillock_dir: '/var/log/faillock'
## 1 for enforcing and 0 for permissive
var_selinux_enforcing: 0
