---
# Example vars file to use when running this playbook to update any required variables
var_rsyslog_authpriv_log: '/var/log/messages'
var_rsyslog_server_name: ''
var_rsyslog_server_port: ''
## udp, tcp, or tls
var_rsyslog_server_protocol: 'tcp'
# Set to true if you want the playbook to install required packages. This requires access to a repo with the required packages.
run_rsyslog_install: false
run_openssl_fips_install: false
run_auditd_install: false
run_time_install: false
run_install_aide: false
run_selinux_install: false
var_time_servers:
  - 'time.vmware.com'
  - 'time2.vmware.com'
## ntpd, chrony, or timesyncd
var_time_type: 'ntpd'
var_pam_faillock_dir: '/var/log/faillock'
## 1 for enforcing and 0 for permissive
var_selinux_enforcing: 0
