control 'VCLD-80-000005' do
  title 'The vCenter VAMI service must generate information to monitor remote access.'
  desc %q(Remote access can be exploited by an attacker to compromise the server. By recording all remote access activities, it will be possible to determine the attacker's location, intent, and degree of success.

VAMI uses the "mod_accesslog" module to log information relating to remote requests. These logs can then be piped to external monitoring systems.)
  desc 'check', %q(At the command prompt, run the following command:

# /opt/vmware/cap_lighttpd/sbin/lighttpd -p -f /var/lib/vmware/cap-lighttpd/lighttpd.conf 2>/dev/null|awk '/server\.modules/,/\)/'|grep mod_accesslog

Example result:

"mod_accesslog",

If the "mod_accesslog" is not present, this is a finding.

Note: The command must be run from a bash shell and not from a shell generated by the "appliance shell". Use the "chsh" command to change the shell for the account to "/bin/bash". Refer to KB Article 2100508 for more details:

https://kb.vmware.com/s/article/2100508)
  desc 'fix', 'Navigate to and open:

/opt/vmware/etc/lighttpd/applmgmt-lighttpd.conf

Add the following value in the "server.modules" section:

mod_accesslog

The result should be similar to the following:

server.modules += ("mod_accesslog", "mod_cgi", "mod_magnet", "mod_rewrite")

Restart the service with the following command:

# systemctl restart cap-lighttpd'
  impact 0.5
  tag check_id: 'C-62879r1003689_chk'
  tag severity: 'medium'
  tag gid: 'V-259139'
  tag rid: 'SV-259139r1003691_rule'
  tag stig_id: 'VCLD-80-000005'
  tag gtitle: 'SRG-APP-000016-WSR-000005'
  tag fix_id: 'F-62788r1003690_fix'
  tag cci: ['CCI-000067']
  tag nist: ['AC-17 (1)']

  describe command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/server\\.modules/,/\\)/'|grep mod_accesslog|sed -e 's/^[ ]*//'").stdout.strip do
    it { should cmp '"mod_accesslog",' }
  end
end
