control 'VCLD-80-000096' do
  title 'The vCenter VAMI service must enable honoring the SSL cipher order.'
  desc %q(During a Transport Layer Security (TLS) session negotiation, when choosing a cipher during a handshake, normally the client's preference is used. This is potentially problematic as a malicious, dated, or poorly configured client could select the most insecure cipher offered by the server, even if it supports stronger ones.

If "ssl.honor-cipher-order" is enabled, the "ssl.cipher-list" setting will be treated as an ordered list of cipher values from most preferred to least, left to right.)
  desc 'check', 'At the command prompt, run the following command:

# /opt/vmware/sbin/vami-lighttpd -p -f /opt/vmware/etc/lighttpd/lighttpd.conf 2>/dev/null|grep "ssl\\.honor-cipher-order"

Expected result:

ssl.honor-cipher-order = "enable"

If the output does not match the expected result, this is a finding.

Note: The command must be run from a bash shell and not from a shell generated by the "appliance shell". Use the "chsh" command to change the shell for the account to "/bin/bash". Refer to KB Article 2100508 for more details:

https://kb.vmware.com/s/article/2100508'
  desc 'fix', 'Navigate to and open:

/opt/vmware/etc/lighttpd/lighttpd.conf

Add or reconfigure the following setting:

ssl.honor-cipher-order = "enable"

Restart the service with the following command:

# vmon-cli --restart applmgmt'
  impact 0.5
  tag check_id: 'C-62894r935364_chk'
  tag severity: 'medium'
  tag gid: 'V-259154'
  tag rid: 'SV-259154r935366_rule'
  tag stig_id: 'VCLD-80-000096'
  tag gtitle: 'SRG-APP-000516-WSR-000174'
  tag fix_id: 'F-62803r935365_fix'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  runtime = command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')}").stdout

  describe parse_config(runtime).params['ssl.honor-cipher-order'] do
    it { should cmp '"enable"' }
  end
end
