control 'VCFM-9X-000001' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must limit the number of allowed simultaneous session requests.'
  desc  "
    Denial of service (DoS) is one threat against web servers. Many DoS attacks attempt to consume web server resources in such a way that no more resources are available to satisfy legitimate requests. Mitigation against these threats includes taking steps to limit the number of resources that can be consumed in certain ways.

    VAMI provides the \"maxConnections\" attribute to limit the number of concurrent Transmission Control Protocol (TCP) connections.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null |grep \"server.max-connections\"

    Example result:

    server.max-connections = 1024

    If \"server.max-connections\" is not configured to 1024 or less, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/applmgmt/appliance/applmgmt-lighttpd.conf

    Add or reconfigure the following value:

    server.max-connections = 1024

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000001-WSR-000001'
  tag gid: 'V-VCFM-9X-000001'
  tag rid: 'SV-VCFM-9X-000001'
  tag stig_id: 'VCFM-9X-000001'
  tag cci: ['CCI-000054']
  tag nist: ['AC-10']

  runtime = command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')}").stdout

  describe parse_config(runtime).params['server.max-connections'] do
    it { should cmp <= 1024 }
  end
end
