control 'VCFM-9X-000125' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must protect system resources from hosted applications.'
  desc  "
    Most of the attention to denial-of-service (DoS) attacks focuses on ensuring that systems and applications are not victims of these attacks. However, these systems and applications must also be secured against use to launch such an attack against others.

    A variety of technologies exist to limit, or in some cases eliminate, the effects of DoS attacks. Limiting system resources that are allocated to any user to a bare minimum may also reduce the ability of users to launch some DoS attacks.

    One DoS mitigation is to prevent VAMI from keeping idle connections open for too long.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|grep \"server.max-keep-alive-idle\"

    Example result:

    server.max-keep-alive-idle=30

    If \"server.max-keep-alive-idle\" is not set to 30, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/applmgmt/appliance/applmgmt-lighttpd.conf

    Add or reconfigure the following value:

    server.max-keep-alive-idle = 30

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000516-WSR-000174'
  tag gid: 'V-VCFM-9X-000125'
  tag rid: 'SV-VCFM-9X-000125'
  tag stig_id: 'VCFM-9X-000125'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  runtime = command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')}").stdout

  describe parse_config(runtime).params['server.max-keep-alive-idle'] do
    it { should cmp '30' }
  end
end
