control 'VCFM-9X-000032' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must have resource mappings set to disable the serving of certain file types.'
  desc  "
    Resource mapping is the process of tying a particular file type to a process in the web server that can serve that type of file to a requesting client and to identify which file types are not to be delivered to a client.

    By not specifying which files can and which files cannot be served to a user, the web server could deliver to a user web server configuration files, log files, password files, etc.

    The web server must only allow hosted application file types to be served to a user and all other types must be disabled.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # grep \"url.access-deny\" /etc/lighttpd/lighttpd.conf

    Example result:

    url.access-deny = ( \"~\", \".inc\" )

    If \"url.access-deny\" is not set to \"( \"~\", \".inc\" )\", this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/lighttpd/lighttpd.conf

    Add or reconfigure the following value:

    url.access-deny = ( \"~\", \".inc\" )

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000141-WSR-000083'
  tag gid: 'V-VCFM-9X-000032'
  tag rid: 'SV-VCFM-9X-000032'
  tag stig_id: 'VCFM-9X-000032'
  tag cci: ['CCI-000381']
  tag nist: ['CM-7 a']

  describe parse_config_file(input('lighttpdConf')).params['url.access-deny'] do
    it { should cmp '( "~", ".inc" )' }
  end
end
