control 'VCFM-9X-000005' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must generate information to monitor remote access.'
  desc  "
    Remote access can be exploited by an attacker to compromise the server. By recording all remote access activities, it will be possible to determine the attacker's location, intent, and degree of success.

    The VAMI service uses the \"mod_accesslog\" module to log information relating to remote requests. These logs can then be forwarded to external monitoring systems.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/server\\.modules/,/\\)/'|grep mod_accesslog

    Example result:

    \"mod_accesslog\",

    If the \"mod_accesslog\" is not present, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/lighttpd/modules.conf

    Add the following value in the \"server.modules\" section:

    mod_accesslog

    The result should be similar to the following:

    server.modules = (
      \"mod_access\",
    )

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000016-WSR-000005'
  tag gid: 'V-VCFM-9X-000005'
  tag rid: 'SV-VCFM-9X-000005'
  tag stig_id: 'VCFM-9X-000005'
  tag cci: ['CCI-000067']
  tag nist: ['AC-17 (1)']

  describe command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/server\\.modules/,/\\)/'|grep mod_accesslog|sed -e 's/^[ ]*//'").stdout.strip do
    it { should cmp '"mod_accesslog",' }
  end
end
