---

# PostgreSQL files and paths
var_postgresql_data_dir: '/data/pgdata'
var_log_dir: '/var/log/postgres/'
var_rsyslog_conf_path: '/etc/rsyslog.d/stig-services-postgres.conf'
var_rsyslog_conf_name: 'stig-services-postgres.conf'

# misc variables
var_notify_service_name: 'postgres'
var_log_owner: 'postgres'
var_log_group: 'users'

# postgresql settings
var_max_connections: '100'
var_log_destination: 'stderr'
var_log_line_prefix: '%m %c %x %d %u %r %p %l'
var_log_file_mode: '0600'
var_port: '5432'
var_password_encryption: 'md5'
var_statement_timeout: "1min"
var_fsync: "on"
var_full_page_writes: "on"
var_synchronous_commit: "on"
var_client_min_messages: "error"
var_logging_collector: "on"
var_log_timezone: "UTC"
var_log_connections: "on"
var_log_disconnections: "on"
