control 'VCFM-9X-000129' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must protect against MIME sniffing.'
  desc  "
    MIME sniffing was, and still is, a technique used by some web browsers to examine the content of a particular asset. This is done for the purpose of determining an asset's file format. This technique is useful in the event that there is not enough metadata information present for a particular asset, thus leaving the possibility that the browser interprets the asset incorrectly.

    Although MIME sniffing can be useful to determine an asset's correct file format, it can also cause a security vulnerability. This vulnerability can be quite dangerous both for site owners as well as site visitors. This is because an attacker can leverage MIME sniffing to send an XSS (Cross Site Scripting) attack.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/setenv\\.add-response-header/,/\\)/'|sed -e 's/^[ ]*//'|grep \"X-Content-Type-Options\"

    Example result:

    \"X-Content-Type-Options\" => \"nosniff\",

    If the response header \"X-Content-Type-Options\" is missing or not configured to \"nosniff\", this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/applmgmt/appliance/applmgmt-lighttpd.conf

    If header \"X-Content-Type-Options\" is not present, add the following line to the end of the file:

    setenv.add-response-header += (\"X-Content-Type-Options\" => \"nosniff\")

    If header \"X-Content-Type-Options\" is present and not set to \"nosniff\", update the value as shown below:

    \"X-Content-Type-Options\" => \"nosniff\",

    Note: The last line in the parameter does not need a trailing comma if part of a multi-line configuration.

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000516-WSR-000174'
  tag gid: 'V-VCFM-9X-000129'
  tag rid: 'SV-VCFM-9X-000129'
  tag stig_id: 'VCFM-9X-000129'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  describe command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/setenv\\.add-response-header/,/\\)/'|sed -e 's/^[ ]*//'|grep X-Content-Type-Options") do
    its('stdout.strip') { should match /"X-Content-Type-Options"\s+=>\s+"nosniff"/ }
  end
end
