control 'VCFM-9X-000033' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must have Web Distributed Authoring (WebDAV) disabled.'
  desc  "
    A web server can be installed with functionality that, just by its nature, is not secure. Web Distributed Authoring (WebDAV) is an extension to the HTTP protocol that, when developed, was meant to allow users to create, change, and move documents on a server, typically a web server or web share. Allowing this functionality makes development and deployment much easier for web authors.

    WebDAV is not widely used and has serious security concerns because it may allow clients to modify unauthorized files on the web server.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/server\\.modules/,/\\)/'

    If the output indicates the \"mod_webdav\" module is loaded, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/lighttpd/modules.conf

    Delete or comment out the \"mod_webdav\" line.

    Note: The line may be in an included config and not in the parent config itself.

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000141-WSR-000085'
  tag gid: 'V-VCFM-9X-000033'
  tag rid: 'SV-VCFM-9X-000033'
  tag stig_id: 'VCFM-9X-000033'
  tag cci: ['CCI-000381']
  tag nist: ['CM-7 a']

  modules = command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/server\\.modules/,/\\)/'|sed -e 's/^[ ]*//'|grep mod_").stdout
  if !modules.empty?
    modules.split.each do |result|
      describe result do
        it { should_not match /mod_webdav/ }
      end
    end
  else
    describe 'No modules found...skipping.' do
      skip 'No modules found...skipping.'
    end
  end
end
