---
# vCenter Authentication Variables
vcenter_username: user@example.com
vcenter_password: "{{ vault_vcenter_password }}"
vcenter_host: ip or fqdn

# vCenter validate certificate (true/false)
validate_certs: false

# Get List of VM's (if this value is false, a list of vm's needs to reside in /tmp/vm_machines.txt)
get_vms: true

# Global VM Exclusion list
exclusion_list: vm1|vm2|

# STIG Variables

# VMCH-70-000006
disk_mode_type: persistent

# VMCH-70-000024
vmotion_encryption: opportunistic

# VMCH-70-000029
ft_encryption: ftEncryptionOpportunistic
