# encoding: UTF-8

control 'V-219333' do
  title "The Ubuntu operating system must record time stamps for audit records
that can be mapped to Coordinated Universal Time (UTC) or Greenwich Mean Time
(GMT)."
  desc  "If time stamps are not consistently applied and there is no common
time reference, it is difficult to perform forensic analysis.

    Time stamps generated by the operating system include date and time. Time
is commonly expressed in Coordinated Universal Time (UTC), a modern
continuation of Greenwich Mean Time (GMT), or local time with an offset from
UTC.
  "
  desc  'rationale', ''
  desc  'check', "
    The time zone must be configured to use Coordinated Universal Time (UTC) or
Greenwich Mean Time (GMT). To verify run the following command.

    # sudo timedatectl status | grep -i \"time zone\"
    Timezone: UTC (UTC, +0000)

    If \"Timezone\" is not set to UTC or GMT, this is a finding.
  "
  desc  'fix', "
    To configure the system time zone to use Coordinated Universal Time (UTC)
or Greenwich Mean Time (GMT), run the following command replacing [ZONE] with
UTC or GMT.

    # sudo timedatectl set-timezone [ZONE]
  "
  impact 0.3
  tag severity: 'low'
  tag gtitle: 'SRG-OS-000359-GPOS-00146'
  tag gid: 'V-219333'
  tag rid: 'SV-219333r508662_rule'
  tag stig_id: 'UBTU-18-010503'
  tag fix_id: 'F-21057r305328_fix'
  tag cci: ['V-100889', 'SV-109993', 'CCI-001890']
  tag nist: ['AU-8 b']

  time_zone = command('timedatectl status | grep -i "time zone"').stdout.strip

  describe time_zone do
    it { should match 'UTC' }
  end
end

