control 'VCLD-67-000011' do
  title 'VAMI log files must only be accessible by privileged users.'
  desc  "Log data is essential in the investigation of events. If log data were
to become compromised, competent forensic analysis and discovery of the true
source of potentially malicious system activity would be difficult, if not
impossible, to achieve.

    In addition, access to log records provides information an attacker could
potentially use to their advantage since each event record might contain
communication ports, protocols, services, trust relationships, user names, etc.
  "
  desc  'rationale', ''
  desc  'check', "
    Note: The below command must be run from a bash shell and not from a shell
generated by the \"appliance shell\". Use the \"chsh\" command to change the
shell for the account to \"/bin/bash\".

    At the command prompt, execute the following command:

    # stat -c \"%n has %a permissions and is owned by %U:%G\"
/opt/vmware/var/log/lighttpd/*.log

    Expected result:

    /opt/vmware/var/log/lighttpd/access.log has 640 permissions and is owned by
root:root
    /opt/vmware/var/log/lighttpd/error.log has 640 permissions and is owned by
root:root

    If the output does not match the expected result, this is a finding.
  "
  desc 'fix', "
    At the command prompt, enter the following command:

    # chown root:root /opt/vmware/var/log/lighttpd/*.log
    # chmod 640 /opt/vmware/var/log/lighttpd/*.log
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000118-WSR-000068'
  tag satisfies: ['SRG-APP-000118-WSR-000068', 'SRG-APP-000119-WSR-000069',
'SRG-APP-000120-WSR-000070']
  tag gid: 'V-239721'
  tag rid: 'SV-239721r816791_rule'
  tag stig_id: 'VCLD-67-000011'
  tag fix_id: 'F-42913r679272_fix'
  tag cci: ['CCI-000162', 'CCI-000163', 'CCI-000164']
  tag nist: ['AU-9', 'AU-9', 'AU-9']

  command("find '#{input('logPath')}' -type f -xdev").stdout.split.each do |fname|
    describe file(fname) do
      it { should_not be_more_permissive_than('0640') }
      its('owner') { should eq 'root' }
      its('group') { should eq 'root' }
    end
  end
end
