control 'VCLD-67-000028' do
  title 'VAMI must set the encoding for all text mime types to UTF-8.'
  desc  "Invalid user input occurs when a user inserts data or characters into
a hosted application's data entry field and the hosted application is
unprepared to process that data. This results in unanticipated application
behavior, potentially leading to an application compromise. Invalid user input
is one of the primary methods employed when attempting to compromise an
application.

    An attacker can also enter Unicode into hosted applications in an effort to
break out of the document home or root home directory or to bypass security
checks.
  "
  desc  'rationale', ''
  desc  'check', "
    Note: The below command must be run from a bash shell and not from a shell
generated by the \"appliance shell\". Use the \"chsh\" command to change the
shell for the account to \"/bin/bash\".

    At the command prompt, execute the following command:

    # /opt/vmware/sbin/vami-lighttpd -p -f
/opt/vmware/etc/lighttpd/lighttpd.conf|awk '/mimetype\\.assign/,/\\)/'|grep
\"text/\"|grep -v \"charset=utf-8\"

    If the command returns any value, this is a finding.
  "
  desc 'fix', "
    Navigate to and open /opt/vmware/etc/lighttpd/lighttpd.conf.

    Navigate to the \"mimetype.assign\" block.

    Replace all the mappings whose assigned type is \"text/*\" with mappings
for UTF-8 encoding, as follows:

      \".css\"          =>      \"text/css; charset=utf-8\",
      \".html\"         =>      \"text/html; charset=utf-8\",
      \".htm\"          =>      \"text/html; charset=utf-8\",
      \".js\"           =>      \"text/javascript; charset=utf-8\",
      \".asc\"          =>      \"text/plain; charset=utf-8\",
      \".c\"            =>      \"text/plain; charset=utf-8\",
      \".cpp\"          =>      \"text/plain; charset=utf-8\",
      \".log\"          =>      \"text/plain; charset=utf-8\",
      \".conf\"         =>      \"text/plain; charset=utf-8\",
      \".text\"         =>      \"text/plain; charset=utf-8\",
      \".txt\"          =>      \"text/plain; charset=utf-8\",
      \".spec\"         =>      \"text/plain; charset=utf-8\",
      \".dtd\"          =>      \"text/xml; charset=utf-8\",
      \".xml\"          =>      \"text/xml; charset=utf-8\",
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000251-WSR-000157'
  tag gid: 'V-239735'
  tag rid: 'SV-239735r816819_rule'
  tag stig_id: 'VCLD-67-000028'
  tag fix_id: 'F-42927r679314_fix'
  tag cci: ['CCI-001310']
  tag nist: ['SI-10']

  describe command("/opt/vmware/sbin/vami-lighttpd -p -f /opt/vmware/etc/lighttpd/lighttpd.conf|awk '/mimetype\\.assign/,/\\)/' | grep \"text/\" | grep -v 'charset=utf-8'") do
    its('stdout') { should eq '' }
  end
end
