control 'VCLD-70-000056' do
  title 'VAMI must enable FIPS mode.'
  desc  'Encryption is only as good as the encryption modules utilized. Unapproved cryptographic module algorithms cannot be verified and cannot be relied upon to provide confidentiality or integrity, and DoD data may be compromised due to weak algorithms. FIPS 140-2 is the current standard for validating cryptographic modules.'
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, execute the following command:

    # /opt/vmware/sbin/vami-lighttpd -p -f /opt/vmware/etc/lighttpd/lighttpd.conf 2>/dev/null|grep \"server.fips-mode\"|sed -e 's/^[ ]*//'

    Expected result:

    server.fips-mode                  = \"enable\"

    If the output does not match the expected result, this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for your account to \"/bin/bash\". See KB Article 2100508 for more details.
  "
  desc 'fix', "
    Navigate to and open:

    /opt/vmware/etc/lighttpd/lighttpd.conf

    Add or reconfigure the following value:

    server.fips-mode = \"enable\"

    Restart the service with the following command:

    # vmon-cli --restart applmgmt
  "
  impact 0.3
  tag severity: 'low'
  tag gtitle: 'SRG-APP-000179-WSR-000111'
  tag gid: nil
  tag rid: nil
  tag stig_id: 'VCLD-70-000056'
  tag cci: ['CCI-000803']
  tag nist: ['IA-7']

  runtime = command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')}").stdout

  describe parse_config(runtime).params['server.fips-mode'] do
    it { should cmp '"enable"' }
  end
end
