---

- name: "NT1R-4X-000027 - Disable DHCP for Tier-1 Gateway: {{ var_outer_t1.id }}"
  ansible.builtin.uri:
    url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/tier-1s/{{ var_outer_t1.id }}"
    validate_certs: false
    headers:
      Cookie: "{{ var_jsession_id }}"
      X-XSRF-TOKEN: "{{ var_session_token }}"
    method: PATCH
    body: "{{ lookup('template', './t1rtr_disable_dhcp.json.j2') }}"
    body_format: json
    status_code: 200
  register: response
  changed_when:
    - response.status == 200
