# VMware vSphere 7.0 vCenter Server Appliance rhttpproxy Ansible Role

---

 #---------- Ansible version 2.9.6 --------#

############################################

# Backup files that may be modified in case restoration is needed

- name: Create time stamp
  set_fact:
    backup_timestamp: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"
  tags:
  - perfcharts
  when:
  - create_backups | bool

- name: Backup files...if restoring be sure to restore permissions that original file had!!
  copy:
    remote_src: yes
    src: "{{ item }}"
    dest: "{{ item }}_{{ backup_timestamp }}.bak"
  with_items:
    - '{{ var_config_xml_path }}'
  tags:
  - rhttpproxy
  when:
  - create_backups | bool

############################################

# Title: Envoy must drop connections to disconnected clients.

- name: VCRP-70-000001 - Envoy must drop connections to disconnected clients.
  xml:
    path: '{{ var_config_xml_path }}'
    xpath: '/config/envoy/L4Filter/tcpKeepAliveTimeSec'
    value: '{{ var_config_xml_tcpkeepalivetimesec }}'
    state: present
  tags:
  - VCRP-70-000001
  - rhttpproxy
  notify:
  - restart rhttpproxy
  when:
  - run_config_tcpkeepalivetimesec | bool

############################################

# Title: Envoy must set a limit on established connections.

- name: VCRP-70-000002 - Envoy must set a limit on established connections.
  xml:
    path: '{{ var_config_xml_path }}'
    xpath: '/config/envoy/L4Filter/maxHttpsConnections'
    value: '{{ var_config_xml_maxhttpsconnections }}'
    state: present
  tags:
  - VCRP-70-000002
  - rhttpproxy
  notify:
  - restart rhttpproxy
  when:
  - run_config_maxhttpsconnections | bool

############################################

# Title: Envoy must be configured to operate in FIPS mode.

- name: VCRP-70-000003 - Envoy must be configured to operate in FIPS mode.
  xml:
    path: '{{ var_config_xml_path }}'
    xpath: '/config/vmacore/ssl/fips'
    value: '{{ var_config_xml_fips }}'
    state: present
  tags:
  - VCRP-70-000003
  - rhttpproxy
  notify:
  - restart rhttpproxy
  when:
  - run_config_fips | bool

############################################

# Title: Envoy must use only TLS 1.2 for the protection of client connections.

- name: VCRP-70-000004 - Envoy must use only TLS 1.2 for the protection of client connections.
  xml:
    path: '{{ var_config_xml_path }}'
    xpath: '/config/vmacore/ssl/protocols'
    value: '{{ var_config_xml_tls }}'
    state: present
  tags:
  - VCRP-70-000004
  - rhttpproxy
  notify:
  - restart rhttpproxy
  when:
  - run_config_tls | bool

############################################

# Title: The Envoy private key file must be protected from unauthorized access.

- name: VCRP-70-000005 - The Envoy private key file must be protected from unauthorized access.
  file:
    path: "{{ var_key_path }}"
    state: file
    mode: 0600
    owner: "root"
    group: "root"
  tags:
  - VCRP-70-000005
  - rhttpproxy
  when:
  - run_key_permissions | bool

############################################

# Title: Envoy must exclusively use the HTTPS protocol for client connections.

- name: VCRP-70-000006 - Envoy must exclusively use the HTTPS protocol for client connections. Key
  xml:
    path: '{{ var_config_xml_path }}'
    xpath: '/config/ssl/privateKey'
    value: '{{ var_config_xml_ssl_private_key }}'
    state: present
  tags:
  - VCRP-70-000006
  - rhttpproxy
  notify:
  - restart rhttpproxy
  when:
  - run_config_ssl | bool

- name: VCRP-70-000006 - Envoy must exclusively use the HTTPS protocol for client connections. Cert
  xml:
    path: '{{ var_config_xml_path }}'
    xpath: '/config/ssl/certificate'
    value: '{{ var_config_xml_ssl_cert }}'
    state: present
  tags:
  - VCRP-70-000006
  - rhttpproxy
  notify:
  - restart rhttpproxy
  when:
  - run_config_ssl | bool

- name: VCRP-70-000006 - Envoy must exclusively use the HTTPS protocol for client connections. VECS
  xml:
    path: '{{ var_config_xml_path }}'
    xpath: '/config/ssl/vecsServerName'
    value: '{{ var_config_xml_ssl_vecs }}'
    state: present
  tags:
  - VCRP-70-000006
  - rhttpproxy
  notify:
  - restart rhttpproxy
  when:
  - run_config_ssl | bool

############################################

# Title: Envoy (rhttpproxy) log files must be shipped via syslog to a central log server.

- name: VCRP-70-000007 - Envoy (rhttpproxy) log files must be shipped via syslog to a central log server.
  template:
    src: vmware-services-rhttpproxy.conf.j2
    dest: /etc/vmware-syslog/vmware-services-rhttpproxy.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  notify:
  - restart syslog
  tags:
  - VCRP-70-000007
  - rhttpproxy
  when:
  - run_syslog_config_rhttpproxy | bool

############################################

# Title: Envoy log files must be shipped via syslog to a central log server.

- name: VCRP-70-000008 - Envoy log files must be shipped via syslog to a central log server.
  template:
    src: vmware-services-envoy.conf.j2
    dest: /etc/vmware-syslog/vmware-services-envoy.conf
    owner: root
    group: root
    mode: '0644'
    force: yes
  notify:
  - restart syslog
  tags:
  - VCRP-70-000008
  - rhttpproxy
  when:
  - run_syslog_config_envoy | bool










