---

- name: "NT0R-4X-000051 - Get external interfaces with URPF not set to {{ var_t0rtr_interface_urpf }} for Tier-0 Gateway: {{ var_outer_t0.id }}"
  ansible.builtin.uri:
    url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:Tier0Interface%20AND%20type:EXTERNAL%20AND%20!urpf_mode:{{ var_t0rtr_interface_urpf }}%20AND%20parent_path:?infra?tier-0s?{{ var_outer_t0.id }}*)"
    validate_certs: false
    headers:
      Cookie: "{{ var_jsession_id }}"
      X-XSRF-TOKEN: "{{ var_session_token }}"
    method: GET
    status_code: 200
  register: t0interfaces
  changed_when: false

- name: "NT0R-4X-000051 - Configure URPF on interfaces for Tier-0 Gateway: {{ var_outer_t0.id }}"
  ansible.builtin.uri:
    url: "https://{{ var_nsx_manager }}/policy/api/v1{{ item.path }}"
    validate_certs: false
    headers:
      Cookie: "{{ var_jsession_id }}"
      X-XSRF-TOKEN: "{{ var_session_token }}"
    method: PATCH
    body: "{{ lookup('template', './t0rtr_configure_urpf_on_interface.json.j2') }}"
    body_format: json
    status_code: 200
  when:
    - t0interfaces.json.result_count != 0
  with_items:
    - "{{ t0interfaces.json.results }}"
  register: response
  changed_when:
    - response.status == 200
