---
###################################################################################################################################
- name: Get all Tier-1 Gateways for use in tasks
  tags: [always]
  block:
    - name: Get all Tier-1 Gateways for use in tasks
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/tier-1s"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
        status_code: 200
      register: t1gateways
      changed_when: false

###################################################################################################################################
- name: T1FW-3X-000005 - The NSX-T Tier-1 Gateway Firewall must generate traffic log entries containing information to establish the details of the event.
  tags: [T1FW-3X-000005, T1FW-3X-000006]
  when: run_t1fw_rule_logging | bool
  block:
    - name: T1FW-3X-000005 - The NSX-T Tier-1 Gateway Firewall must generate traffic log entries containing information to establish the details of the event. No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "T1FW-3X-000005 - No Tier-0 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: T1FW-3X-000005 - Loop through Tier-1 Gateways and update firewall rules
      ansible.builtin.include_tasks:
        file: t1fw_update_rule_logging_get_policies.yml
      with_items:
        - "{{ t1gateways.json.results }}"
      when:
        - t1gateways.json.result_count != 0
        - not var_outer_t1.disable_firewall
      loop_control:
        loop_var: var_outer_t1
        label: "T1 Info: {{ var_outer_t1.id }}"

##################################################################################################################################
- name: T1FW-3X-000011
  tags: [T1FW-3X-000011]
  when: run_t1fw_syslog_tls | bool
  block:
    - name: T1FW-3X-000011 - The NSX-T Tier-1 Gateway Firewall must be configured to use the TLS or LI-TLS protocols to configure and secure communications with the central audit server.
      ansible.builtin.debug:
        msg: "T1FW-3X-000011 - This control must be manually remediated."
      changed_when: false

##################################################################################################################################
- name: T1FW-3X-000019 - The NSX-T Tier-1 Gateway Firewall must block outbound traffic containing denial-of-service (DoS) attacks to protect against the use of internal information systems to launch any DoS attacks against other networks or endpoints.
  tags: [T1FW-3X-000019, T1FW-3X-000028]
  when: run_t1fw_floodprotprof | bool
  block:
    - name: T1FW-3X-000019 - The NSX-T Tier-1 Gateway Firewall must block outbound traffic containing (DoS) attacks to protect against the use of internal information systems to launch any DoS attacks against other networks or endpoints. No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "T1FW-3X-000019 - No Tier-1 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: T1FW-3X-000019 - Check if flood protection profiles exists
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:(GatewayFloodProtectionProfile))"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
        status_code: 200
      register: t1_floodprot_prof
      changed_when: false
      when:
        - t1gateways.json.result_count != 0

    - name: T1FW-3X-000019 - Create a flood protection profile if doesn't exist
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/flood-protection-profiles/{{ var_t1fw_fpp_name }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './t1fw_create_flood_prot_prof.json.j2') }}"
        body_format: json
        status_code: 200
      register: response_create
      when:
        - t1gateways.json.result_count != 0
        - t1_floodprot_prof.json.result_count == 0
      changed_when:
        - response_create.status == 200

    - name: T1FW-3X-000019 - Update existing flood protection profiles
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/flood-protection-profiles/{{ item.id }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './t1fw_upd_flood_prot_prof.json.j2') | to_json }}"
        body_format: json
        status_code: 200
      with_items:
        - "{{ t1_floodprot_prof.json.results }}"
      register: response_update
      when:
        - t1gateways.json.result_count != 0
        - t1_floodprot_prof.json.result_count != 0
        - (item.udp_active_flow_limit != var_t1fw_fpp_udp_active_flow_limit) or
          (item.icmp_active_flow_limit != var_t1fw_fpp_icmp_active_flow_limit) or
          (item.tcp_half_open_conn_limit != var_t1fw_fpp_tcp_half_open_conn_limit) or
          (item.other_active_conn_limit != var_t1fw_fpp_other_active_conn_limit)
      changed_when:
        - response_update.status == 200

    - name: T1FW-3X-000019 - Loop through Tier-1 Gateways and apply flood protection profile if needed
      ansible.builtin.include_tasks:
        file: t1fw_apply_flood_protection_profile.yml
      with_items:
        - "{{ t1gateways.json.results }}"
      when:
        - t1gateways.json.result_count != 0
      loop_control:
        loop_var: var_outer_t1
        label: "t1 Info: {{ var_outer_t1.id }}"

###################################################################################################################################
- name: T1FW-3X-000021 - The NSX-T Tier-1 Gateway Firewall must deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception).
  tags: [T1FW-3X-000021]
  when: run_t1fw_default_rule_action | bool
  block:
    - name: T1FW-3X-000021 - The NSX-T Tier-1 Gateway Firewall must deny network communications traffic by default and allow network communications traffic by exception (i.e., deny all, permit by exception). No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "T1FW-3X-000021 - No Tier-1 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: T1FW-3X-000021 - Loop through Tier-1 Gateways and update default firewall rule action
      ansible.builtin.include_tasks:
        file: t1fw_update_default_rule_action.yml
      with_items:
        - "{{ t1gateways.json.results }}"
      when:
        - t1gateways.json.result_count != 0
      loop_control:
        loop_var: var_outer_t1
        label: "t1 Info: {{ var_outer_t1.id }}"

###################################################################################################################################
- name: T1FW-3X-000030 - The NSX-T Tier-1 Gateway Firewall must apply ingress filters to traffic that is inbound to the network through any active external interface.
  tags: [T1FW-3X-000030]
  when: run_t1fw_gwfw_rules | bool
  block:
    - name: T1FW-3X-000030 - The NSX-T Tier-1 Gateway Firewall must apply ingress filters to traffic that is inbound to the network through any active external interface.
      ansible.builtin.debug:
        msg: "T1FW-3X-000030 - This control must be manually remediated."
      changed_when: false

###################################################################################################################################
# T1FW-3X-000036 - The NSX-T Tier-1 Gateway Firewall must configure SpoofGuard to block outbound IP packets that contain illegitimate packet attributes.
- name: T1FW-3X-000036 - The NSX-T Tier-1 Gateway Firewall must configure SpoofGuard to block outbound IP packets that contain illegitimate packet attributes.
  tags: [T1FW-3X-000036]
  when: run_t1fw_spoofguard_prof | bool
  block:
    - name: T1FW-3X-000036 - The NSX-T Distributed Firewall must configure SpoofGuard to block outbound IP packets that contain illegitimate packet attributes. No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "T1FW-3X-000036 - No Tier-1 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: T1FW-3X-000036 - List SpoofGuard segment profiles excluding the default profile which cannot be modified
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:SpoofGuardProfile%20AND%20!id:default-spoofguard-profile)"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
      register: t1fw_spfgrd_prof_list
      changed_when: false
      when:
        - t1gateways.json.result_count != 0

    - name: T1FW-3X-000036 - Create SpoofGuard segment profile with port binding enabled if none exist
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/spoofguard-profiles/{{ var_t1fw_spoofguard_profile_name }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PUT
        body: "{{ lookup('template', './t1fw_spoof_guard_prof_create.json.j2') }}"
        body_format: json
        status_code: 200
      when:
        - t1fw_spfgrd_prof_list.json.result_count == 0
        - t1gateways.json.result_count != 0
      register: t1fw_spfgrd_prof_wportbind_create
      changed_when:
        - t1fw_spfgrd_prof_wportbind_create.status == 200

    - name: T1FW-3X-000036 - Update SpoofGuard segment profiles with port binding disabled
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/spoofguard-profiles/{{ item.id }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './t1fw_spoof_guard_prof_patch.json') }}"
        body_format: json
        status_code: 200
      with_items:
        - "{{ t1fw_spfgrd_prof_list.json.results }}"
      when:
        - t1fw_spfgrd_prof_list.json.result_count != 0
        - not item.address_binding_allowlist
        - t1gateways.json.result_count != 0
      register: t1fw_spfgrd_prof_wportbind_update
      changed_when:
        - t1fw_spfgrd_prof_wportbind_update.status == 200

    - name: T1FW-3X-000036 - Get all segments
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/segments"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
      register: t1fwsegmentlist
      changed_when: false
      when:
        - t1gateways.json.result_count != 0

    - name: T1FW-3X-000036 - Loop through segments and update Spoofguard profile if necessary
      ansible.builtin.include_tasks:
        file: t1fw_segments_update_spoofguard.yml
      with_items: "{{ t1fwsegmentlist.json.results }}"
      when:
        - t1fwsegmentlist.json.result_count != 0
        - t1gateways.json.result_count != 0
