---

###################################################################################################################################
- name: Get all Tier-1 Gateways for use in tasks
  tags: [always]
  block:
    - name: Get all Tier-1 Gateways for use in tasks
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/tier-1s"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
        status_code: 200
      register: t1gateways
      changed_when: false

###################################################################################################################################
- name: NT1R-4X-000016 - The NSX Tier-1 Gateway must be configured to have all inactive interfaces removed.
  tags: [NT1R-4X-000016]
  when: run_t1rtr_remove_inactive_interfaces | bool
  block:
    - name: NT1R-4X-000016 - The NSX Tier-1 Gateway must be configured to have all inactive interfaces removed. No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "NT1R-4X-000016 - No Tier-1 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: NT1R-4X-000016 - The NSX Tier-1 Gateway must be configured to have all inactive interfaces removed.
      ansible.builtin.debug:
        msg: "NT1R-4X-000016 - This control must be manually remediated."
      changed_when: false
      when:
        - t1gateways.json.result_count != 0

###################################################################################################################################
- name: NT1R-4X-000027 - The NSX Tier-1 Gateway must be configured to have the DHCP service disabled if not in use.
  tags: [NT1R-4X-000027]
  when: run_t1rtr_disable_dhcp | bool
  block:
    - name: NT1R-4X-000027 - The NSX Tier-1 Gateway must be configured to have the DHCP service disabled if not in use. No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "NT1R-4X-000027 - No Tier-1 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: NT1R-4X-000027 - Loop through Tier-1 Gateways and disable dhcp if needed
      ansible.builtin.include_tasks:
        file: t1rtr_disable_dhcp.yml
      with_items:
        - "{{ t1gateways.json.results }}"
      when:
        - t1gateways.json.result_count != 0
        - var_outer_t1.dhcp_config_paths is defined
        - var_outer_t1.id not in var_t1rtr_gateways_with_dhcp_enabled
      loop_control:
        loop_var: var_outer_t1
        label: "T1 Info: {{ var_outer_t1.id }}"

###################################################################################################################################
- name: NT1R-4X-000102 - The NSX Tier-1 Gateway must be configured to advertise a hop limit of at least 32 in Router Advertisement messages for IPv6 stateless auto-configuration deployments.
  tags: [NT1R-4X-000102]
  when: run_t1rtr_ipv6_hop_limit | bool
  block:
    - name: NT1R-4X-000102 - The NSX Tier-1 Gateway must be configured to advertise a hop limit of at least 32 in Router Advertisement messages for IPv6 stateless auto-configuration deployments. No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "NT1R-4X-000102 - No Tier-1 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: NT1R-4X-000102 - Check to see if IPv6 forwarding is enabled
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/infra/global-config"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
        status_code: 200
      register: ipv6enabled
      changed_when: false
      when:
        - t1gateways.json.result_count != 0

    - name: NT1R-4X-000102 - Find IPv6 ND Profiles with a hop limit set incorrectly
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:Ipv6NdraProfile%20AND%20!ra_config.hop_limit:(64%20OR%20{{ var_t1rtr_ipv6_hop_limit }}))"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
        status_code: 200
      register: badipv6profiles
      changed_when: false
      when:
        - t1gateways.json.result_count != 0
        - ipv6enabled.json.l3_forwarding_mode == "IPV4_AND_IPV6"

    - name: "NT1R-4X-000102 - Update IPv6 profiles with a hop limit set incorrectly to {{ var_t1rtr_ipv6_hop_limit }}"
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1{{ item.path }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './t1rtr_update_ipv6_ndra_profile.json.j2') | to_json }}"
        body_format: json
        status_code: 200
      with_items:
        - "{{ badipv6profiles.json.results }}"
      register: ipv6ndraupdate
      when:
        - t1gateways.json.result_count != 0
        - ipv6enabled.json.l3_forwarding_mode == "IPV4_AND_IPV6"
        - badipv6profiles.json.result_count != 0
      changed_when:
        - ipv6ndraupdate.status == 200

###################################################################################################################################
- name: NT1R-4X-000107 - The NSX Tier-1 Gateway must be configured to have multicast disabled if not in use.
  tags: [NT1R-4X-000107]
  when: run_t1rtr_disable_multicast | bool
  block:
    - name: NT1R-4X-000107 - The NSX Tier-1 Gateway must be configured to have multicast disabled if not in use. No Tier-1 Gateways found.
      ansible.builtin.debug:
        msg: "NT1R-4X-000107 - No Tier-1 Gateways found."
      changed_when: false
      when:
        - t1gateways.json.result_count == 0

    - name: NT1R-4X-000107 - Find enabled Tier-1 Multicast Policies
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1/search?query=(resource_type:PolicyMulticastConfig%20AND%20enabled:true)"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: GET
        status_code: 200
      register: multicastenabled
      changed_when: false
      when:
        - t1gateways.json.result_count != 0

    - name: NT1R-4X-000107 - Disable multicast on Tier-1s
      ansible.builtin.uri:
        url: "https://{{ var_nsx_manager }}/policy/api/v1{{ item.path }}"
        validate_certs: false
        headers:
          Cookie: "{{ var_jsession_id }}"
          X-XSRF-TOKEN: "{{ var_session_token }}"
        method: PATCH
        body: "{{ lookup('template', './t1rtr_disable_multicast_gateway.json.j2') }}"
        body_format: json
        status_code: 200
      with_items:
        - "{{ multicastenabled.json.results }}"
      register: multicastupdate
      when:
        - t1gateways.json.result_count != 0
        - multicastenabled.json.result_count != 0
        # extract T1 ID from path and see if it's in list given
        - item.path | regex_search('\/infra\/tier-1s\/(.*?)\/', '\\1') | first not in var_t1rtr_gateways_with_multicast_enabled
      changed_when:
        - multicastupdate.status == 200
