---
# Vars file for running playbook on a chroot
# To create backups of files modified under /tmp set to true
create_backups: false
# Disable the DoD login banner
photon_5_defaults_run_phtn_50_000005_dod_banner: false
# Set to true if you want the playbook to install required packages. This requires access to a repo with the required packages.
## rsyslog install
photon_5_defaults_run_phtn_50_000241: false
## openssl fips provider install
photon_5_defaults_run_phtn_50_000013: false
## auditd install
photon_5_defaults_run_phtn_50_000016_auditd_install: false
## aide install
photon_5_defaults_run_phtn_50_000127: false
