---
# handlers file for photon3

- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: restart auditd
  ansible.builtin.command: killproc auditd -TERM && systemctl start auditd

- name: reload auditd
  ansible.builtin.command: /sbin/augenrules --load

- name: restart syslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: restart ntp
  ansible.builtin.systemd:
    name: ntpd
    state: restarted

- name: restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
