control 'VCFM-9X-000030' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must explicitly disable Multipurpose Internet Mail Extensions (MIME) mime mappings based on "Content-Type".'
  desc  "
    Controlling what a user of a hosted application can access is part of the security posture of the web server. Any time a user can access more functionality than is needed for the operation of the hosted application poses a security issue. A user with too much access can view information that is not needed for the user's job role, or the user could use the function in an unintentional manner.

    A MIME mapping tells the web server what type of program various file types and extensions are and what external utilities or programs are needed to execute the file type. A limited number of MIME types must be configured manually, and automatic mapping must be disabled.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|grep \"mimetype.use-xattr\"

    Example result:

    mimetype.use-xattr=\"disable\"

    If \"mimetype.use-xattr\" is not set to \"disable\", this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/applmgmt/appliance/applmgmt-lighttpd.conf

    Add or reconfigure the following value:

    mimetype.use-xattr = \"disable\"

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000141-WSR-000081'
  tag gid: 'V-VCFM-9X-000030'
  tag rid: 'SV-VCFM-9X-000030'
  tag stig_id: 'VCFM-9X-000030'
  tag cci: ['CCI-000381']
  tag nist: ['CM-7 a']

  runtime = command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')}").stdout

  describe parse_config(runtime).params['mimetype.use-xattr'] do
    it { should cmp '"disable"' }
  end
end
