control 'VCFM-9X-000128' do
  title 'The VMware Cloud Foundation vCenter VAMI Lighttpd service must implement prevent rendering inside a frame or iframe on another site.'
  desc  "
    Clickjacking, also known as a “UI redress attack”, is when an attacker uses multiple transparent or opaque layers to trick a user into clicking on a button or link on another page when they were intending to click on the top level page. Thus, the attacker is “hijacking” clicks meant for their page and routing them to another page, most likely owned by another application, domain, or both.

    Using a similar technique, keystrokes can also be hijacked. With a carefully crafted combination of stylesheets, iframes, and text boxes, a user can be led to believe they are typing in the password to their email or bank account but are instead typing into an invisible frame controlled by the attacker.
  "
  desc  'rationale', ''
  desc  'check', "
    At the command prompt, run the following:

    # /usr/sbin/lighttpd -p -f /etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/setenv\\.add-response-header/,/\\)/'|sed -e 's/^[ ]*//'|grep \"X-Frame-Options\"

    Example result:

    \"X-Frame-Options\" => \"Deny\",

    If the response header \"X-Frame-Options\" is missing or not configured to \"Deny\", this is a finding.

    Note: The command must be run from a bash shell and not from a shell generated by the \"appliance shell\". Use the \"chsh\" command to change the shell for the account to \"/bin/bash\". Refer to KB Article 2100508 for more details:

    https://knowledge.broadcom.com/external/article?legacyId=2100508
  "
  desc 'fix', "
    Navigate to and open:

    /etc/applmgmt/appliance/applmgmt-lighttpd.conf

    If header \"X-Frame-Options\" is not present, add the following line to the end of the file:

    setenv.add-response-header += (\"X-Frame-Options\" => \"Deny\")

    If header \"X-Frame-Options\" is present and not set to \"Deny\", update the value as shown below:

    \"X-Frame-Options\" => \"Deny\",

    Note: The last line in the parameter does not need a trailing comma if part of a multi-line configuration.

    Restart the service with the following command:

    # systemctl restart lighttpd
  "
  impact 0.5
  tag severity: 'medium'
  tag gtitle: 'SRG-APP-000516-WSR-000174'
  tag gid: 'V-VCFM-9X-000128'
  tag rid: 'SV-VCFM-9X-000128'
  tag stig_id: 'VCFM-9X-000128'
  tag cci: ['CCI-000366']
  tag nist: ['CM-6 b']

  describe command("#{input('lighttpdBin')} -p -f #{input('lighttpdConf')} 2>/dev/null|awk '/setenv\\.add-response-header/,/\\)/'|sed -e 's/^[ ]*//'|grep X-Frame-Options") do
    its('stdout.strip') { should match /"X-Frame-Options"\s+=>\s+"Deny"/ }
  end
end
