---

- name: restart syslog
  ansible.builtin.service:
    name: syslog
    state: restarted

- name: restart vpostgres
  ansible.builtin.command: vmon-cli --restart vmware-vpostgres

- name: reload vpostgres config
  ansible.builtin.command: /opt/vmware/vpostgres/current/bin/psql -U postgres -c "SELECT pg_reload_conf();"
