---
# Pull Photon role from Gitlab
roles:
  - src: https://github.com/vmware/dod-compliance-and-automation/tree/master/photon/3.0/ansible/vmware-photon-3.0-stig-ansible-hardening
    scm: git
    version: master
