- hosts: all
  roles:
    - role: vmware-photon-3.0-stig-ansible-hardening
      vars:
        run_sshd_listenaddress: false
        var_syslog_authpriv_log: '/var/log/messages'
    - role: vpostgres
      vars:
        run_enable_pgaudit: false
        run_configure_pgaudit: false
        var_password_encryption: md5
