---
# Is the server connected to the proper repository to download PowerShell Core (default true)
# If the server is not connected, ensure the rpm for powershell is located within the files directory of the role.
pwsh_repo: true

# For when installed via RPM (set name when needed);
powershell_rpm: powershell-7.2.0-1.rh.x86_64.rpm

# Do you need to copy PowerCLI modules into place? (default false)
# If you need to copy PowerCLI modules into place, set to true and ensure modules are in ~/esxi-remediation-local/file_location/Modules
copy_powercli_modules: false

# Use role vault set false if no
esx_local_vault: true

# vCenter Accessibility Variables
vcenter_hostname: example.vsphere.local
vcenter_username: administrator@vsphere.local
vcenter_password: "{{ vault_vcenter_password }}"

# vCenter validate certificate (true/false)
validate_certs: false

# Is ~/esxi-remediation-local/file_location (in this case, the files directory of the role.)
file_location: files

# Ansible VMware Collection Dictionary variables (add/delete/modify groups as needed)
# ESXi Hosts (Add as many as you have)
# If the passwords differ then make vaulted values unique
esxi_hosts:
  esxi_one:
    hostname: example.domain.com # ESXi Hostname (switch to IP if hostname is not supported/setup)
    username: root # Needed for ansible module call
    password: "{{ vault_esxi_password }}" # Needed for ansible module call
    allowed_ip: 192.168.x.x # ESXI-70-000056
    vswitch: vswitch_name # ESXI-70-000059
    portgroup: portgroup_name # ESXI-70-000059
    nics: vmnic0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    mtu: 1500 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    number_of_ports: 128 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    vlan_id: 0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
  esxi_two:
    hostname: example.domain.com # ESXi Hostname (switch to IP if hostname is not supported/setup)
    username: root # Needed for ansible module call
    password: "{{ vault_esxi_password }}" # Needed for ansible module call
    allowed_ip: 192.168.x.x # ESXI-70-000056
    vswitch: vswitch_name # ESXI-70-000059
    portgroup: portgroup_name # ESXI-70-000059
    nics: vmnic0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    mtu: 1500 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    number_of_ports: 128 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    vlan_id: 0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
  esxi_three:
    hostname: example.domain.com # ESXi Hostname (switch to IP if hostname is not supported/setup)
    username: root # Needed for ansible module call
    password: "{{ vault_esxi_password }}" # Needed for ansible module call
    allowed_ip: 192.168.x.x # ESXI-70-000056
    vswitch: vswitch_name # ESXI-70-000059
    portgroup: portgroup_name # ESXI-70-000059
    nics: vmnic0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    mtu: 1500 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    number_of_ports: 128 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    vlan_id: 0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
  esxi_four:
    hostname: example.domain.com # ESXi Hostname (switch to IP if hostname is not supported/setup)
    username: root # Needed for ansible module call
    password: "{{ vault_esxi_password }}" # Needed for ansible module call
    allowed_ip: 192.168.x.x # ESXI-70-000056
    vswitch: vswitch_name # ESXI-70-000059
    portgroup: portgroup_name # ESXI-70-000059
    nics: vmnic0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    mtu: 1500 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    number_of_ports: 128 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)
    vlan_id: 0 # Change this value as needed (it is passed as an argument in ESXI-70-000059,60,61 but is not a STIG item)

# ESXI-70-000037
domain_name: example.local
domain_username: insert_username
domain_password: "{{ vault_domain_password }}"

# STIG Variables

# ESXI-70-000001
esxi_lockdown_level: lockdownNormal

# ESXI-70-000002 ('Comma-seperated list of users expected to have DCUI Access')
dcui_access: root

# ESXI-70-000004
syslog_server_hostname: udp://changeme:514

# ESXI-70-000005
account_lock_failures: 3

# ESXI-70-000006
account_unlock_time: 900

# ESXI-70-000007
dod_welcome_banner: |
  You are accessing a U.S. Government (USG) Information System (IS) that is provided for USG-authorized use only.

  By using this IS (which includes any device attached to this IS), you consent to the following conditions:

  -The USG routinely intercepts and monitors communications on this IS for purposes including, but not limited to, penetration testing, COMSEC monitoring, network operations and defense, personnel misconduct (PM), law enforcement (LE), and counterintelligence (CI) investigations.

  -At any time, the USG may inspect and seize data stored on this IS.

  -Communications using, or data stored on, this IS are not private, are subject to routine monitoring, interception, and search, and may be disclosed or used for any USG-authorized purpose.

  -This IS includes security measures (e.g., authentication and access controls) to protect USG interests- -not for your personal benefit or privacy.

  -Notwithstanding the above, using this IS does not constitute consent to PM, LE or CI investigative searching or monitoring of the content of privileged communications, or work product, related to personal representation or services by attorneys, psychotherapists, or clergy,
    and their assistants. Such communications and work product are private and confidential. See User Agreement for details.

# ESXI-70-000030
log_level: info

# ESXI-70-000031
password_complexity: similar=deny retry=3 min=disabled,disabled,disabled,disabled,15

# ESXI-70-000032
password_history: 5

# ESXI-70-000034 (lockdown requires value to be set to false if this is desired to be left as a finding, switch value to true.)
set_managed_object_browser: "false"

# ESXI-70-000039
esx_admins_group: admins

# ESXI-70-000041
shell_int_timeout: 120

# ESXI-70-000042
shell_timeout: 600

# ESXI-70-000043
dcui_timeout: 120

# ESXI-70-000045
syslog_scratch: "[] /scratch/log"

# ESXI-70-000046 - NTP Servers
ntpserver1: changeme
ntpserver2: changeme

# ESXI-70-000047
vib_accept_level: PartnerSupported

# ESXI-70-000054 - CHAP Variables
chap_name: insert_chap_name
chap_password: "{{ vault_chap_password }}"
mutual_chap_name: insert_mutual_chap_name
mutual_chap_password: "{{ vault_mutual_chap_password }}"

# ESXI-70-000055
share_force_salting: 2

# ESXI-70-000058
block_guest_bpdu: 1

# ESXI-70-000062
dvfilter_bind_ip_address: ""

# ESXI-70-000074
depracted_ssl_protocols: tlsv1,tlsv1.1,sslv3

# ESXI-70-000079
suppress_shell_warning: 0

# ESXI-70-000081
suppress_hyper_warning: 0

# ESXI-70-000086
syslog_cert_check: "true"

# ESXI-70-000087
mem_eager_zero: 1

# ESXI-70-000088
api_timeout: 30

# ESXI-70-000089
host_client_timeout: 600

# ESXI-70-000091
password_max_days: 90
