apiVersion: crd.antrea.io/v1alpha1
kind: NetworkPolicy
metadata:
  name: cert-manager-dns
  namespace: cert-manager
spec:
  priority: 5
  tier: securityops
  appliedTo:
    - podSelector:
        matchLabels:
          app: cert-manager
  egress:
    - action: Allow
      toServices:
       - name: kube-dns
         namespace: kube-system
      name: AllowToCoreDNS
