name: Lint code for syntax issues on pushes
permissions:
  contents: read

on: push

jobs:
  lint-inspec-all:
    runs-on: ubuntu-latest
    container:
      image: pipelinecomponents/rubocop
      options: --pull always
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Run Rubocop
        run: |
          rubocop --config .rubocop.yml .

  list-ansible-repos:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Ansible Repo List
        id: matrix
        run: |
          echo "value=$(find . -name '*-stig-ansible-*' -printf '%P\n' | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_OUTPUT"

# # OPTION ONE: run each as its own job - better option as each individual job can fail
# # Problems include: repo gets cloned for each job, ansible-lint (and deps) install for each job
#   run-ansible-lint:
#     needs: list-ansible-repos
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         value: ${{ fromJson(needs.list-ansible-repos.outputs.matrix) }}
#     steps:
#       - name: Clone Repo
#         uses: actions/checkout@v4
#       - name: Install Ansible and ansible-lint
#         run: |
#           pip3 install ansible ansible-lint
#       - name: Run ansible-lint
#         run: |
#           ansible-lint ${{ matrix.value }}


# OPTION TWO: run all within one job - better option as repo isn't cloned over and over, deps installed one time
  run-ansible-lint:
    needs: list-ansible-repos
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Install Ansible and ansible-lint
        run: |
          pip3 install ansible ansible-lint
      - name: Run ansible-lint
        run: |
          echo "rootdir = $(pwd)"
          for prj in ${{ join(fromJSON(needs.list-ansible-repos.outputs.matrix), ' ') }}
            do
              echo " "
              echo "**********************************************************************************************************************"
              echo " RUNNING ansible-lint on"
              echo "/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/$prj"
              echo "----------------------------------------------------------------------------------------------------------------------"
              cd "/home/runner/work/dod-compliance-and-automation/dod-compliance-and-automation/$prj"
              ansible-lint . --offline || command_failed=1
              echo "**********************************************************************************************************************"
            done

          if [ ${command_failed:-0} -eq 1 ]
          then
            echo "************ LINTING ERROR(S) OCCURRED ***********"
            exit 1
          fi

          echo "************ SUCCESS *****************"
          exit 0
