name: lint

on:
  pull_request:
  push:

jobs:
  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: install cookstyle and run linter
      - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
      - run: |
          gem install cookstyle
          cookstyle ./
