control 'VCLD-70-000004' do
  title 'VAMI must be configured to monitor remote access.'
  desc %q(Remote access can be exploited by an attacker to compromise the server. By recording all remote access activities, it will be possible to determine the attacker's location, intent, and degree of success.

VAMI uses the "mod_accesslog" module to log information relating to remote requests. These logs can then be piped to external monitoring systems.

)
  desc 'check', %q[At the command prompt, run the following command:

# /opt/vmware/sbin/vami-lighttpd -p -f /opt/vmware/etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/server\.modules/,/\\)/'|grep mod_accesslog|sed -e 's/^[ ]*//'

Expected result:

"mod_accesslog",

If the output does not match the expected result, this is a finding.

Note: The command must be run from a bash shell and not from a shell generated by the "appliance shell". Use the "chsh" command to change the shell for the account to "/bin/bash". Refer to KB Article 2100508 for more details:

https://kb.vmware.com/s/article/2100508]
  desc 'fix', 'Navigate to and open:

/opt/vmware/etc/lighttpd/lighttpd.conf

Add the following value in the "server.modules" section:

mod_accesslog

The result should be similar to the following:

    server.modules                    = (
        "mod_access",
        "mod_accesslog",
        "mod_proxy",
        "mod_cgi",
        "mod_rewrite",
        "mod_magnet",
        "mod_setenv",
    )

Restart the service with the following command:

# vmon-cli --restart applmgmt'
  impact 0.5
  tag check_id: 'C-60323r888464_chk'
  tag severity: 'medium'
  tag gid: 'V-256648'
  tag rid: 'SV-256648r888466_rule'
  tag stig_id: 'VCLD-70-000004'
  tag gtitle: 'SRG-APP-000016-WSR-000005'
  tag fix_id: 'F-60266r888465_fix'
  tag satisfies: ['SRG-APP-000016-WSR-000005', 'SRG-APP-000093-WSR-000053']
  tag cci: ['CCI-000067', 'CCI-001462']
  tag nist: ['AC-17 (1)', 'AU-14 (2)']

  describe command("/opt/vmware/sbin/vami-lighttpd -p -f /opt/vmware/etc/lighttpd/lighttpd.conf 2>/dev/null|awk '/server\.modules/,/\)/'|grep mod_accesslog|sed -e 's/^[ ]*//'").stdout.strip do
    it { should eq '"mod_accesslog",' }
  end
end
